/**
 * Mutation test of the guards themselves: puts each historical bug back, in a throwaway git
 * worktree, and requires the guard written for it to FAIL. A guard that stays green with
 * its own bug reinstated protects nothing — this is how "fixed at the origin" is proved,
 * not asserted.
 *
 *   pnpm verificar:guardas            # every mutation
 *   pnpm verificar:guardas M-05 n8n   # only the named ones
 *
 * Each mutation names: the file it breaks, the exact text it swaps back, and the command
 * that must fail. Exit 1 if any mutation survives (its guard stayed green).
 */
import { execFileSync, spawnSync } from "node:child_process";
import { existsSync, mkdtempSync, readFileSync, rmSync, symlinkSync, writeFileSync } from "node:fs";
import { tmpdir } from "node:os";
import { join, resolve } from "node:path";

interface Mutation {
  id: string;
  bug: string;
  files: string[];
  from: string;
  to: string;
  /**
   * More swaps in the same files, for a bug two layers now guard: one layer reinstated alone
   * leaves the other catching it, and the mutation would "escape" while the bug stays fixed.
   */
  also?: Array<{ from: string; to: string }>;
  guard: string[];
}

const MUTATIONS: Mutation[] = [
  {
    id: "WA-selo",
    bug: "a porta pública do n8n aceitava mensagem forjada com o telefone de uma cliente real",
    files: ["supabase/functions/turn/index.ts"],
    from: "    signingSecret !== \"\" &&\n    !isRetry &&",
    to: "    false &&\n    !isRetry &&",
    guard: ["pnpm", "-s", "vitest", "run", "tests/function-drift.test.ts"],
  },
  {
    id: "WA-janela-no-fim",
    bug: "last_inbound_at gravado no fim do turno esticava a janela de 24h",
    files: ["supabase/functions/turn/index.ts"],
    from: "      cost_brl: spent,\n      updated_at: new Date().toISOString(),",
    to: "      cost_brl: spent,\n      last_inbound_at: new Date().toISOString(),\n      updated_at: new Date().toISOString(),",
    guard: ["pnpm", "-s", "vitest", "run", "tests/function-drift.test.ts"],
  },
  {
    id: "WA-envio-desligado",
    bug: "o envio pela Cloud API saía ligado antes do número e dos valores do sócio",
    files: ["n8n/workflows/whatsapp-envio.json"],
    from: "const CANAL_ATIVO = false;",
    to: "const CANAL_ATIVO = true;",
    guard: ["pnpm", "-s", "vitest", "run", "tests/n8n-whatsapp-send.test.ts"],
  },
  {
    id: "WA-canal-forjado",
    bug: "o n8n mandava mensagem pelo WhatsApp com base no campo channel que qualquer um escreve",
    files: ["n8n/workflows/turno-da-agente.json"],
    from: '"leftValue": "={{ $json.sealed }}"',
    to: '"leftValue": "={{ $(\'Mensagem recebida\').first().json.body.channel === \'whatsapp\' }}"',
    guard: ["pnpm", "-s", "vitest", "run", "tests/n8n-workflows.test.ts"],
  },
  {
    id: "WA-1-janela",
    bug: "a régua mandava texto livre fora da janela de 24h, que a Meta recusa",
    files: ["supabase/functions/turn/index.ts"],
    from: "const delivery = deliveryFor(kind, renderCtx, lastInbound);",
    to: "const delivery = { via: \"text\" as const, body: text };",
    guard: ["pnpm", "-s", "vitest", "run", "tests/function-drift.test.ts"],
  },
  {
    id: "H-2-preco-da-loja",
    bug: '"por 116 eu levo" (o preço real do pix) lido como barganha: a venda ficava sem link',
    files: ["src/agent/interpret.ts"],
    from: "if (!prices.some((p) => Math.abs(p - value) <= 1)) return true;",
    to: "return true;",
    guard: ["pnpm", "-s", "vitest", "run", "tests/interpret.test.ts"],
  },
  {
    id: "H-2-barganha",
    bug: '"faz por 100 que eu levo" contava como decisão e mandava o link (Tati)',
    files: ["supabase/functions/turn/index.ts"],
    from: 'if (namesOwnPrice(inbound.body ?? "", shopPrices, shopPercents)) interpretation = { ...interpretation, wants_to_buy: false };',
    to: "",
    guard: ["pnpm", "-s", "vitest", "run", "tests/function-drift.test.ts"],
  },
  {
    id: "H-2-numero",
    bug: "a leitura por número desligada: nenhum preço inventado é visto",
    files: ["src/agent/interpret.ts"],
    from: "if (cue === null || value < cue) continue;",
    to: "continue;",
    guard: ["pnpm", "-s", "vitest", "run", "tests/interpret.test.ts"],
  },
  {
    id: "M-05",
    bug: 'afrouxamento: "tiro … dúvida" removido mesmo com concessão depois (1ª versão da M-05)',
    files: ["src/agent/guardrails.ts"],
    from: "(?![^.!?]{0,20}\\b(?:um\\s+pou(?:c|qu)\\w+|mais|pra\\s+voce|para\\s+voce)\\b)",
    to: "(?![\\s,]*\\b(?:e|mais)\\b)",
    guard: ["pnpm", "-s", "dev:gates", "--base=HEAD", "--fail-on-loosen"],
  },
  {
    id: "pouquinho",
    bug: '"Eu tiro um pouquinho." passava: pouc\\w+ não casa "pouquinho"',
    files: ["src/agent/guardrails.ts"],
    from: "(um\\s+pou(?:c|qu)\\w+|mais|pra\\s+voce)",
    to: "(um\\s+pouc\\w+|mais|pra\\s+voce)",
    guard: ["pnpm", "-s", "vitest", "run", "tests/change-registry.test.ts"],
  },
  {
    id: "M-07-numero",
    bug: "qualquer número vira garantia (a regra por contexto, antes da regra do número)",
    files: ["src/agent/guardrails.ts"],
    from: "if (days === ctx.config.delivery.warrantyDays) {",
    to: "if (true) {",
    guard: ["pnpm", "-s", "vitest", "run", "tests/prepaid-deadline-fuzz.test.ts"],
  },
  {
    id: "M-07-recusa",
    bug: 'a recusa larga liberava "não tem como passar de 2 dias"',
    files: ["src/agent/guardrails.ts"],
    // The whole regex as it was: the denial governing any of these verbs, with anything after.
    from: "(?:(?:consigo|conseguimos|posso|podemos|da\\s+pra|tem\\s+como)\\s+)?(?:te\\s+|lhe\\s+)?(?:garant\\w*|promet\\w*)\\s+(?:que\\s+(?:chegue|chega|receba|recebe)\\s+(?:em\\s+)?(?:ate\\s+)?)?$/",
    to: "(?:\\w+\\s+){0,2}?(?:garant\\w*|promet\\w*|consig\\w*|posso|podemos|da\\s+pra|tem\\s+como|sei\\s+se)\\b[^,;:]*$/",
    guard: ["pnpm", "-s", "vitest", "run", "tests/prepaid-deadline-fuzz.test.ts"],
  },
  {
    id: "M-08",
    bug: '"No antecipado, um dia só." e "chega em uma semana" passavam: um/uma e semanas não eram contados',
    files: ["src/agent/guardrails.ts"],
    from: "|n?uma?|dois|duas|tres|quatro|cinco|seis|sete|oito|nove|dez|quinze|vinte|trinta)\\s*(dias?|semanas?)\\b/g;",
    to: "|dois|duas|tres|quatro|cinco|seis|sete|oito|nove|dez|quinze|vinte|trinta)\\s*(dias?)\\b/g;",
    guard: ["pnpm", "-s", "vitest", "run", "tests/prepaid-deadline-fuzz.test.ts"],
  },
  {
    id: "M-08-chegada",
    bug: '"Em 2 dias ele está aí na sua casa." passava no antecipado: sem verbo da lista, não era prazo',
    files: ["src/agent/guardrails.ts"],
    from: "(!named && ctx.paymentPath === \"prepay\" && (deadlineTalk || averageWord))",
    to: "(!named && ctx.paymentPath === \"prepay\" && (/\\b(?:prazo|cheg\\w*|entreg\\w*|receb\\w*|lev[ae]\\w*|demor\\w*|envi\\w*|despach\\w*|post\\w*)\\b/.test(sentence) || averageWord))",
    guard: ["pnpm", "-s", "vitest", "run", "tests/prepaid-deadline-fuzz.test.ts"],
  },
  {
    id: "M-08-semanas",
    bug: '"Na entrega chega em 1 a 2 semanas." passava: a checagem de faixa só lia dias',
    files: ["src/agent/guardrails.ts"],
    from: "(\\d{1,2})\\s*(dias|semanas)/g)) {",
    to: "(\\d{1,2})\\s*dias/g)) {",
    // Since M-10 the count loop also judges the end of a week range: both layers go back.
    also: [
      { from: "if (!week && /\\d\\s*(?:a|e|ate)\\s*$/.test(before)) continue;", to: "if (/\\d\\s*(?:a|e|ate)\\s*$/.test(before)) continue;" },
    ],
    guard: ["pnpm", "-s", "vitest", "run", "tests/prepaid-deadline-fuzz.test.ts"],
  },
  {
    id: "M-08-uso",
    bug: '"Em 3 dias ele está aí pra você se adaptar." passava: a palavra de uso em qualquer lugar da oração isentava',
    files: ["src/agent/guardrails.ts"],
    // 2026-09-28: no wearing exemption any more — the fallback needs delivery talk. The bug is an
    // exemption by the wearing word anywhere.
    from: "(!named && ctx.paymentPath === \"prepay\" && (deadlineTalk || averageWord))",
    to: "(!named && ctx.paymentPath === \"prepay\" && ((deadlineTalk && !/\\b(?:de\\s+uso|acostum\\w*|adapt\\w*)\\b/.test(sentence)) || averageWord))",
    guard: ["pnpm", "-s", "vitest", "run", "tests/prepaid-deadline-fuzz.test.ts"],
  },
  {
    id: "M-08-governo",
    bug: "\"Pode trocar quando chegar é 7 dias.\" passava: a contagem da garantia era isenta sem forma de garantia que a governasse",
    files: ["src/agent/guardrails.ts"],
    from: "if ((purpose || governedBefore || takenAfterReturn || hers) && tailOk",
    to: "if (tailOk",
    guard: ["pnpm", "-s", "vitest", "run", "tests/prepaid-deadline-fuzz.test.ts"],
  },
  {
    id: "M-08-cauda",
    bug: "\"Pode trocar em 7 dias, quando ele chega.\" passava: o que vinha depois da contagem não era julgado",
    files: ["src/agent/guardrails.ts"],
    from: "const tailOk =\n            /^\\s*$/.test(tail) ||",
    to: "const tailOk =\n            true ||",
    guard: ["pnpm", "-s", "vitest", "run", "tests/prepaid-deadline-fuzz.test.ts"],
  },
  {
    id: "M-08-oracao-propria",
    bug: "\"Chega em 7 dias pra trocar.\" passava: a chegada na própria oração da contagem não era julgada",
    files: ["src/agent/guardrails.ts"],
    from: "tailOk && !ARRIVAL.test(notDelivery(own))) continue;",
    to: "tailOk) continue;",
    guard: ["pnpm", "-s", "vitest", "run", "tests/prepaid-deadline-fuzz.test.ts"],
  },
  {
    id: "M-08-ate-quando",
    bug: "\"O prazo até quando chegar é de 7 dias pra trocar.\" passava: a âncora de chegada era retirada mesmo depois de \"até/o prazo/o tempo\"",
    files: ["src/agent/guardrails.ts"],
    from: "(?<!\\b(?:ate|pra|para|prazo|tempo)\\s)\\b(?:${START}",
    to: "\\b(?:${START}",
    guard: ["pnpm", "-s", "vitest", "run", "tests/change-registry.test.ts"],
  },
  {
    id: "M-08-tomada",
    bug: "\"Pode trocar, e quando o colete chegar é de 7 dias.\" passava: \"é/são/tem N\" depois da troca valia com a chegada no meio",
    files: ["src/agent/guardrails.ts"],
    from: "            new RegExp(\n              String.raw`\\bprazo\\s+(?:pra|para|de)\\s+${RETV}\\s+${TAKES}|(?:\\bse\\s+(?:(?!\\b(?:cheg|receb|entreg|lev[ae]|demor|envi|despach|post)\\w*)[^,;:])*?|\\b(?:pra|para)\\s+|\\be\\s+so\\s+)${RETV}${OBJECT}\\s*[,:]\\s*(?:(?:o|seu)\\s+prazo\\s+)?${TAKES}`,\n            ).test(sb);",
    to: "            new RegExp(TAKES).test(sb);",
    guard: ["pnpm", "-s", "vitest", "run", "tests/prepaid-deadline-fuzz.test.ts"],
  },
  {
    id: "M-08-roteiro",
    bug: "\"Você tem 7 dias pra trocar ou devolver contando do dia que receber.\" (fala do roteiro) era vetada no antecipado: o início da contagem não conhecia \"contando\"",
    files: ["src/agent/guardrails.ts"],
    from: "|contando(?:\\s+a\\s+partir)?|a\\s+contar)\\s+d[aeo]",
    to: "|a\\s+contar)\\s+d[aeo]",
    guard: ["pnpm", "-s", "vitest", "run", "tests/change-registry.test.ts"],
  },
  {
    id: "M-08-objeto",
    bug: "\"Você tem 7 dias pra trocar de tamanho.\" era vetada: o verbo de troca não aceitava objeto",
    files: ["src/agent/guardrails.ts"],
    from: "const OBJECT = String.raw`(?:\\s+(?:de|o|a|pelo|por\\s+outro)\\s+(?:tamanho|produto|colete|numero)(?:\\s+(?:certo|correto|ideal|maior|menor))?)?`;",
    to: "const OBJECT = \"\";",
    guard: ["pnpm", "-s", "vitest", "run", "tests/change-registry.test.ts"],
  },
  {
    id: "M-08-presenca",
    bug: "\"Pode trocar em 7 dias, e o colete é seu.\" passava: a chegada em palavras depois da garantia não era lida",
    files: ["src/agent/guardrails.ts"],
    // 2026-09-28: her having it lives in the one ARRIVAL now.
    from: String.raw`|ja\s+tem|(?:tem|tera|vai\s+ter)\s+(?:o\s+(?:seu\s+)?colete|ele)|ja\s+(?:(?:esta|ta)\s+)?(?:vest|us)\w*|e\s+(?:tod[oa]\s+)?(?:seu|sua)|(?:esta|ta|estara|estar|fica)\s+(?:(?:aqui|ai|la)\s+)?(?:com\s+(?:voce|ele)|contigo|em\s+casa))\b/;`,
    to: String.raw`)\b/;`,
    guard: ["pnpm", "-s", "vitest", "run", "tests/prepaid-deadline-fuzz.test.ts"],
  },
  {
    id: "M-08-recebermos",
    bug: "\"No pix, são 7 dias depois que recebermos.\" passava: \"são/é N\" + início da contagem isentava sem palavra de troca",
    files: ["src/agent/guardrails.ts"],
    from: "const hers = startHer && /\\bvoce\\s+(?:tem|tera)\\s+(?:ate\\s+)?$/.test(sb);",
    to: "const hers = taken;",
    guard: ["pnpm", "-s", "vitest", "run", "tests/prepaid-deadline-fuzz.test.ts"],
  },
  {
    id: "M-08-ponto-e-virgula",
    bug: "\"No pix você tem 7 dias pra trocar; a entrega também.\" passava: depois de \";\" a entrega e o tempo não eram julgados",
    files: ["src/agent/guardrails.ts"],
    from: "tail = tail.replace(/\\beu\\s+fico\\s+aqui\\b[^;,]*?\\bcom\\s+voce\\s+do\\s+pedido\\s+ate\\s+a\\s+entrega\\b/g, \" \");",
    to: "tail = tail.split(\";\")[0]! + (tail.includes(\";\") ? \";\" : \"\");",
    guard: ["pnpm", "-s", "vitest", "run", "tests/prepaid-deadline-fuzz.test.ts"],
  },
  {
    id: "M-08-locucao",
    bug: "\"No pix, você tem 7 dias pra trocar do pedido até a entrega.\" passava: a locução do roteiro saía da cauda em qualquer lugar",
    files: ["src/agent/guardrails.ts"],
    from: "tail = tail.replace(/\\beu\\s+fico\\s+aqui\\b[^;,]*?\\bcom\\s+voce\\s+do\\s+pedido\\s+ate\\s+a\\s+entrega\\b/g, \" \");",
    to: "tail = tail.replace(/\\bdo\\s+pedido\\s+ate\\s+a\\s+entrega\\b/g, \" \");",
    guard: ["pnpm", "-s", "vitest", "run", "tests/prepaid-deadline-fuzz.test.ts"],
  },
  {
    id: "M-08-prazo-de-troca",
    bug: "\"O prazo pra trocar é de 7 dias.\" era vetada: \"prazo\" nunca era tomado pela garantia, nem depois da troca",
    files: ["src/agent/guardrails.ts"],
    from: "String.raw`\\bprazo\\s+(?:pra|para|de)\\s+${RETV}\\s+${TAKES}|(?:\\bse",
    to: "String.raw`(?:\\bse",
    guard: ["pnpm", "-s", "vitest", "run", "tests/change-registry.test.ts"],
  },
  {
    id: "M-08-troca-solta",
    bug: "\"No antecipado a troca é fácil, e o prazo é 7 dias.\" passava: qualquer palavra de troca antes tomava \"o prazo é N\"",
    files: ["src/agent/guardrails.ts"],
    from: "            new RegExp(\n              String.raw`\\bprazo\\s+(?:pra|para|de)\\s+${RETV}\\s+${TAKES}|(?:\\bse\\s+(?:(?!\\b(?:cheg|receb|entreg|lev[ae]|demor|envi|despach|post)\\w*)[^,;:])*?|\\b(?:pra|para)\\s+|\\be\\s+so\\s+)${RETV}${OBJECT}\\s*[,:]\\s*(?:(?:o|seu)\\s+prazo\\s+)?${TAKES}`,\n            ).test(sb);",
    to: "            new RegExp(TAKES).test(sb) &&\n            !ARRIVAL.test(notDelivery(sb.slice(lastRet.index)));",
    guard: ["pnpm", "-s", "vitest", "run", "tests/prepaid-deadline-fuzz.test.ts"],
  },
  {
    id: "M-08-copula",
    bug: "\"No pix tem garantia e são 7 dias.\" passava: o \"e\" de \"garantia e são\" era lido como \"é\"",
    files: ["src/agent/guardrails.ts"],
    from: "(?:\\s+(?:no\\s+\\w+|tambem|pode\\s+ser\\s+\\w+|vale|a\\s+mesma|o\\s+mesmo|gratis|gratuita|igual))*(?:\\s+(?:e|sao|fica)(?:\\s+(?:tambem|a\\s+mesma|o\\s+mesmo|gratis|gratuita|igual))*)?\\s*:?\\s+",
    to: "(?:\\s+(?:no\\s+\\w+|tambem|pode\\s+ser\\s+\\w+|e|sao|fica|vale|a\\s+mesma|o\\s+mesmo|gratis|gratuita|igual))*\\s*:?\\s+",
    guard: ["pnpm", "-s", "vitest", "run", "tests/prepaid-deadline-fuzz.test.ts"],
  },
  {
    id: "O-04",
    bug: 'a régua chamando a Edge Function com a credencial "Gemini API"',
    files: ["n8n/workflows/relogio-da-regua.json"],
    from: '"name": "Supabase service_role"',
    to: '"name": "Gemini API"',
    guard: ["pnpm", "-s", "vitest", "run", "tests/n8n-workflows.test.ts"],
  },
  {
    id: "neverError",
    bug: "neverError escondendo o 401 como execução verde",
    files: ["n8n/workflows/relogio-da-regua.json"],
    from: '"neverError": false',
    to: '"neverError": true',
    guard: ["pnpm", "-s", "vitest", "run", "tests/n8n-workflows.test.ts"],
  },
  {
    id: "espelho",
    bug: "o gate de produção diverge do repositório",
    files: ["supabase/functions/turn/guardrails.ts"],
    from: 'name: "price_promise",',
    to: 'name: "price_promise", // drift',
    guard: ["pnpm", "-s", "vitest", "run", "tests/function-drift.test.ts"],
  },
  {
    id: "provedor-5xx",
    bug: 'o provedor parseia a página de erro 504 como JSON ("Unexpected token u")',
    files: ["src/llm/providers/http.ts"],
    from: "const transient = response.status >= 500 || response.status === 429;",
    to: "const transient = false;",
    guard: ["pnpm", "-s", "vitest", "run", "tests/provider-http.test.ts"],
  },
  {
    id: "5.8",
    bug: "o webhook de venda não escreve o estágio (o funil parava em pedido_criado)",
    files: ["supabase/functions/turn/index.ts"],
    from: 'if (reached) await persistStage(conversation.id, (conversation.stage as Stage | null) ?? "novo", reached);',
    to: "void reached;",
    guard: ["pnpm", "-s", "vitest", "run", "tests/order-stage.test.ts"],
  },
  {
    id: "7.4",
    bug: "a régua de silêncio terminava sem ninguém escrever perdido (o silence_3 com cupom inativo sai pelo ramo vazio)",
    files: ["supabase/functions/turn/index.ts"],
    from: '      await leave("canceled");\n      skipped.push({\n        followupId: row.id,\n        reason:\n          kind === "deferred_reply"',
    to: '      await mark("canceled");\n      skipped.push({\n        followupId: row.id,\n        reason:\n          kind === "deferred_reply"',
    guard: ["pnpm", "-s", "vitest", "run", "tests/order-stage.test.ts"],
  },
  {
    id: "7.4-retry",
    bug: "a nova tentativa de turno rodava depois de ela escrever de novo (respondia a mensagem velha)",
    files: ["supabase/functions/turn/index.ts"],
    from: 'const claimed = await mark("sent");\n      if (!Array.isArray(claimed) || claimed.length === 0) {',
    to: 'const claimed = await mark("sent");\n      if (false) {',
    guard: ["pnpm", "-s", "vitest", "run", "tests/order-stage.test.ts"],
  },
  {
    id: "7.4-envio",
    bug: "o lembrete de silêncio saía depois de ela responder (a varredura gravava e enviava antes de fechar a linha)",
    files: ["supabase/functions/turn/index.ts"],
    from: '    if (!(await leave("sent"))) {\n      skipped.push({ followupId: row.id, reason: "ela respondeu antes do envio" });\n      return;\n    }\n',
    to: '    await leave("sent");\n',
    guard: ["pnpm", "-s", "vitest", "run", "tests/order-stage.test.ts"],
  },
  {
    id: "dois-pedidos",
    bug: "o cancelamento de um pedido calava a véspera de outro pedido do mesmo lead",
    files: ["src/agent/followups.ts", "supabase/functions/turn/followups.ts"],
    from: "const theirs = (f: ExistingFollowup) => !orderId || !f.orderId || f.orderId === orderId;",
    to: "const theirs = (_f: ExistingFollowup) => true;",
    guard: ["pnpm", "-s", "vitest", "run", "tests/followups.test.ts"],
  },
  {
    id: "dois-pedidos-estagio",
    bug: "o cancelamento de um pedido travava em recusado a conversa cujo outro pedido foi entregue",
    files: ["src/agent/followups.ts", "supabase/functions/turn/followups.ts"],
    from: 'return reached === "recusado" && others.some((s) => !isOrderDead(s)) ? null : reached;',
    to: "return reached;",
    guard: ["pnpm", "-s", "vitest", "run", "tests/order-stage.test.ts"],
  },
  {
    id: "R10.4-armado",
    bug: "o lembrete de 15 minutos depois do link nunca era agendado (a régua não recebia o ponto de parada)",
    files: ["supabase/functions/turn/index.ts"],
    from: "const rows = rulerFor(from, stopPoint, postponed, linkInReply).map((f) => ({",
    to: "const rows = rulerFor(from, \"before_size\", postponed, linkInReply).map((f) => ({",
    guard: ["pnpm", "-s", "vitest", "run", "tests/order-stage.test.ts"],
  },
  {
    id: "R10.4-resposta",
    bug: "a resposta dela não cancelava o lembrete de checkout (\"conseguiu finalizar?\" depois de ela falar)",
    files: ["supabase/functions/turn/index.ts"],
    from: '${withCheckout ? "or=(kind.like.silence_*,kind.eq.checkout_reminder)" : "kind=like.silence_*"}',
    to: "kind=like.silence_*",
    guard: ["pnpm", "-s", "vitest", "run", "tests/order-stage.test.ts"],
  },
  {
    id: "R10.4-venda",
    bug: "a venda não cancelava o lembrete de checkout (\"conseguiu finalizar?\" para quem comprou)",
    files: ["src/agent/followups.ts", "supabase/functions/turn/followups.ts"],
    from: "    cancel: scheduled.filter((f) => inSilenceRuler(f.kind)).map((f) => f.kind),",
    to: '    cancel: scheduled.filter((f) => f.kind.startsWith("silence_")).map((f) => f.kind),',
    guard: ["pnpm", "-s", "vitest", "run", "tests/order-stage.test.ts"],
  },
  {
    id: "R10.4-duplicado",
    bug: "o silence_1 adiado depois da meia-noite rearmava o lembrete de checkout que já tinha saído",
    files: ["src/agent/followups.ts", "supabase/functions/turn/followups.ts"],
    from: "  return at === -1 ? ruler : ruler.slice(at);",
    to: "  return ruler;",
    guard: ["pnpm", "-s", "vitest", "run", "tests/order-stage.test.ts"],
  },
  {
    id: "R10.4-palavra-link",
    bug: "a palavra link numa oferta armava o lembrete de um link que nunca saiu",
    files: ["supabase/functions/turn/index.ts"],
    from: 'if (linkSentRecently([...earlier, replyText], CHECKOUT_BASES)) return "link_sent";',
    to: 'if (/\\blink\\b/i.test(replyText)) return "link_sent";',
    guard: ["pnpm", "-s", "vitest", "run", "tests/order-stage.test.ts"],
  },
  {
    id: "M-08-se-chegada",
    bug: "\"No pix, se precisar receber e trocar, são 7 dias.\" passava: o \"se\" atravessava a chegada até a troca",
    files: ["src/agent/guardrails.ts", "supabase/functions/turn/guardrails.ts"],
    from: String.raw`\bse\s+(?:(?!\b(?:cheg|receb|entreg|lev[ae]|demor|envi|despach|post)\w*)[^,;:])*?|`,
    to: String.raw`\bse\s+[^,;:]*?|`,
    guard: ["pnpm", "-s", "vitest", "run", "tests/prepaid-deadline-fuzz.test.ts"],
  },
  {
    id: "M-10",
    bug: "\"Na entrega chega em uma semana / em 5 dias / em dez dias\" passavam: a contagem da entrega dava `continue`",
    files: ["src/agent/guardrails.ts", "supabase/functions/turn/guardrails.ts"],
    from: 'if ((named && path !== "prepay") || (',
    to: 'if (named && path === "cod") continue;\n        if ((false) || (',
    guard: ["pnpm", "-s", "vitest", "run", "tests/prepaid-deadline-fuzz.test.ts"],
  },
  {
    id: "M-10-sem-nome",
    bug: "\"Chega em uma semana.\" passava no caminho da entrega: sem nome de caminho, a contagem não era julgada",
    files: ["src/agent/guardrails.ts", "supabase/functions/turn/guardrails.ts"],
    from: '(averageShaped ? path === "cod" : deadlineTalk || by === "denial")',
    to: '(averageShaped ? path === "cod" : by === "denial")',
    guard: ["pnpm", "-s", "vitest", "run", "tests/prepaid-deadline-fuzz.test.ts"],
  },
  {
    id: "M-10-inicio",
    bug: "\"de um a três dias\" passava com a entrega configurada de 2 a 3: só o fim da faixa por extenso era julgado",
    files: ["src/agent/guardrails.ts", "supabase/functions/turn/guardrails.ts"],
    from: "if (start < codDaysMin || days > codDaysMax)",
    to: "if (days > codDaysMax)",
    guard: ["pnpm", "-s", "vitest", "run", "tests/change-registry.test.ts"],
  },
  {
    id: "M-10-semana",
    bug: "\"Na entrega chega em uma semana\" passava com o máximo configurado em 7: semana não cabe na faixa da entrega",
    files: ["src/agent/guardrails.ts", "supabase/functions/turn/guardrails.ts"],
    from: "if (week) return `delivery in weeks contradicts",
    to: "if (false) return `delivery in weeks contradicts",
    guard: ["pnpm", "-s", "vitest", "run", "tests/change-registry.test.ts"],
  },
  {
    id: "M-10-cabecalho",
    bug: "\"Pagou no pix? Chega em 2 dias.\" passava no caminho da entrega: o nome do caminho na frase anterior não era lido",
    files: ["src/agent/guardrails.ts", "supabase/functions/turn/guardrails.ts"],
    from: "        if (names(COD_NAME, own) || names(PREPAY_NAME, own)) return null;",
    to: "        return null;",
    guard: ["pnpm", "-s", "vitest", "run", "tests/prepaid-deadline-fuzz.test.ts"],
  },
  {
    id: "M-10-faixa-pix",
    bug: "\"No pix chega em 1 a 3 dias.\" passava no caminho da entrega: a checagem de faixa só lia \"antecipado\" como nome",
    files: ["src/agent/guardrails.ts", "supabase/functions/turn/guardrails.ts"],
    from: 'const named = found.by === "name" || found.by === "after" || found.path === "prepay" ? found.path : null;',
    to: "const named = /antecipa/.test(t) ? found.path : null;",
    guard: ["pnpm", "-s", "vitest", "run", "tests/change-registry.test.ts"],
  },
  {
    id: "M-10-media-negada",
    bug: "\"Nada de pix. Em média 5 dias úteis.\" passava no COD: a forma da média ia para a regra do antecipado mesmo com o antecipado negado",
    files: ["src/agent/guardrails.ts", "supabase/functions/turn/guardrails.ts"],
    from: '(averageShaped ? path === "cod" : deadlineTalk || by === "denial")',
    to: '(averageShaped ? false : deadlineTalk || by === "denial")',
    guard: ["pnpm", "-s", "vitest", "run", "tests/prepaid-deadline-fuzz.test.ts"],
  },
  {
    id: "M-10-sombra",
    bug: "\"Te mando o link e chega em 1 a 3 dias.\" era vetada no COD: a lista local da faixa (link, cartão e antes soltos) sombreava a da M-10",
    files: ["src/agent/guardrails.ts", "supabase/functions/turn/guardrails.ts"],
    // 2026-09-28: one list of names now; the bug is the loose "link / cartão / antes" in it.
    from: String.raw`|online|deposito|pelo\s+link|`,
    to: String.raw`|online|deposito|link|cartao|antes|pelo\s+link|`,
    guard: ["pnpm", "-s", "vitest", "run", "tests/change-registry.test.ts"],
  },
  {
    id: "M-10-negacao",
    bug: "\"Nada de pix. Chega em 1 a 3 dias.\" (o argumento do roteiro) era vetada no COD, e \"Nada de pix. Chega em 5 dias, depende da região.\" passava: o nome do antecipado negado nomeava o antecipado",
    files: ["src/agent/guardrails.ts", "supabase/functions/turn/guardrails.ts"],
    from: "if (denier && !(denier[1]?.startsWith",
    to: "if (false && !(denier[1]?.startsWith",
    guard: ["pnpm", "-s", "vitest", "run", "tests/prepaid-deadline-fuzz.test.ts"],
  },
  {
    id: "M-10-negacao-depois",
    bug: "\"Pix não precisa. Chega em 1 a 3 dias.\" era vetada no COD: a negação depois do nome não era lida",
    files: ["src/agent/guardrails.ts", "supabase/functions/turn/guardrails.ts"],
    from: String.raw`          if (/^\s*nao(?:\s+precisa)?\s*(?:[.!,;:?]|$)/.test(rest)) continue;`,
    to: "",
    guard: ["pnpm", "-s", "vitest", "run", "tests/prepaid-deadline-fuzz.test.ts"],
  },
  {
    id: "M-10-nao-quer",
    bug: "\"Não quer pagar no pix? Chega em 2 dias.\" passaria no COD: a pergunta que oferece o pix lida como negação",
    files: ["src/agent/guardrails.ts", "supabase/functions/turn/guardrails.ts"],
    from: String.raw`!(denier[1]?.startsWith("quer") && /^[^.!\n]*\?/.test(s.slice(at))) &&`,
    to: "",
    guard: ["pnpm", "-s", "vitest", "run", "tests/prepaid-deadline-fuzz.test.ts"],
  },
  {
    id: "M-10-nome-da-entrega",
    bug: "\"Na entrega você tem 7 dias pra trocar.\" era vetada: o nome do caminho da entrega era lido como chegada",
    files: ["src/agent/guardrails.ts", "supabase/functions/turn/guardrails.ts"],
    from: String.raw`.replace(/\b(?:(?:no\s+)?pag\w*\s+)?na\s+entrega\b|\bpag\w*\s+na\s+(?:porta|mao(?:\s+do\s+entregador)?)\b/g, " ")`,
    to: "",
    guard: ["pnpm", "-s", "vitest", "run", "tests/prepaid-deadline-fuzz.test.ts"],
  },
  {
    id: "pedido-de-outra-cliente",
    bug: "o toque pós-pedido lia o pedido pelo order_id sem o lead: numa colisão de external_id citava o pedido de outra cliente",
    files: ["supabase/functions/turn/index.ts"],
    from: "`orders?id=eq.${row.order_id}&lead_id=eq.${lead.id}&select=",
    to: "`orders?id=eq.${row.order_id}&select=",
    guard: ["pnpm", "-s", "vitest", "run", "tests/order-stage.test.ts"],
  },
  {
    id: "hermes-trecho",
    bug: "proposta do Hermes com trecho inventado passando pela validação",
    files: ["src/dev/hermes-core.ts"],
    from: "else if (!e?.trecho || !norm(text).includes(norm(e.trecho)))",
    to: "else if (false)",
    guard: ["pnpm", "-s", "vitest", "run", "tests/hermes-core.test.ts"],
  },
  {
    id: "hermes-lgpd",
    bug: "CPF e telefone saindo para o modelo sem máscara",
    files: ["src/dev/hermes-core.ts"],
    from: '.replace(/\\b\\d{3}\\.?\\d{3}\\.?\\d{3}-?\\d{2}\\b/g, "[cpf]")',
    to: "",
    guard: ["pnpm", "-s", "vitest", "run", "tests/hermes-core.test.ts"],
  },
  {
    id: "kit-preco",
    bug: "qualquer preço de kit passa (o gate não lê os kits do config)",
    files: ["src/agent/guardrails.ts"],
    from: "...kits.map((k) => k.priceBrl)]);",
    to: "...kits.map((k) => k.priceBrl), 220]);",
    guard: ["pnpm", "-s", "vitest", "run", "tests/kits.test.ts"],
  },
  {
    id: "kit-quantidade",
    bug: "quantidade inventada pelo modelo troca o link por um kit que ela não pediu",
    files: ["src/agent/interpret.ts"],
    from: "i.units !== null && i.units > 1 && !QUANTITY_CUE.test(text) && !namesCount(text, i.units) ? null : i.units",
    to: "i.units",
    guard: ["pnpm", "-s", "vitest", "run", "tests/quantity.test.ts"],
  },
  {
    id: "apto-12",
    bug: '"Apto 12, G" perdia o tamanho (números descartados no complemento)',
    files: ["n8n/workflows/venda-confirmada.json"],
    from: "complemento.split(/[^A-Z0-9]+/)",
    to: "complemento.split(/[^A-Z]+/)",
    guard: ["pnpm", "-s", "vitest", "run", "tests/n8n-sale-mapping.test.ts"],
  },
  {
    id: "kit-banco",
    bug: 'orders.size só aceitava uma letra — toda venda de kit ("M,G") falhava no insert',
    files: ["supabase/migrations/0010_order_kit_sizes.sql"],
    from: "check (size ~ '^(P|M|G|GG|XGG)(,(P|M|G|GG|XGG))*$')",
    to: "check (size ~ '^(P|M|G|GG|XGG)$')",
    guard: ["pnpm", "-s", "vitest", "run", "tests/n8n-sale-mapping.test.ts"],
  },
  {
    id: "kit-retry",
    bug: 'a nova tentativa reaplicava o tamanho e virava "G e G"',
    files: ["supabase/functions/turn/index.ts"],
    from: "replayed ? [] : saidSizes,",
    to: "saidSizes,",
    guard: ["pnpm", "-s", "vitest", "run", "tests/function-drift.test.ts"],
  },
  {
    id: "kit-caminho",
    bug: '"na entrega você leva com 30%" passava — percentual de outro caminho',
    files: ["src/agent/guardrails.ts"],
    from: "return offers.filter((o) => (paths.size !== 1 || paths.has(o.path)) && units.has(o.units));",
    to: "return offers.filter((o) => units.has(o.units));",
    guard: ["pnpm", "-s", "vitest", "run", "tests/kits.test.ts"],
  },
  {
    id: "kit-calca",
    bug: '"uso 42, ela 46" pedia a letra à cliente, que chutava (o número de cada peça não passava pela tabela)',
    files: ["supabase/functions/turn/index.ts"],
    from: "interpretation.unit_pants.map(sizeFromDressSize)",
    to: "[]",
    guard: ["pnpm", "-s", "vitest", "run", "tests/function-drift.test.ts"],
  },
  {
    id: "placar-reenvio",
    bug: "o placar contava como link repetido o reenvio que a cliente pediu (achado do Hermes)",
    files: ["src/dev/persona-scorecard.ts"],
    from: "if (!asksForLink(customer) && links.some(",
    to: "if (links.some(",
    guard: ["pnpm", "-s", "vitest", "run", "tests/persona-scorecard.test.ts"],
  },
  {
    id: "kit-comparacao",
    bug: 'o gate vetava a fala do script "R$ 116,91 em vez de R$ 129,90" (preço de comparação lido como oferta)',
    files: ["src/agent/guardrails.ts"],
    from: "if (comparedAgainst) continue;",
    to: "",
    guard: ["pnpm", "-s", "vitest", "run", "tests/kits.test.ts"],
  },
  {
    id: "kit-correcao",
    bug: '"na verdade o meu é G" virava o tamanho da outra peça',
    files: ["src/agent/interpret.ts"],
    from: "if (ownSize && said.length === 1) return",
    to: "if (false) return",
    guard: ["pnpm", "-s", "vitest", "run", "tests/quantity.test.ts"],
  },
  {
    id: "kit-calca-quantidade",
    bug: '"uso 42" contava como pista de quantidade e liberava units inventado',
    files: ["src/agent/interpret.ts"],
    from: "const QUANTITY_CUE = /\\b(?:kit|",
    to: "const QUANTITY_CUE = /\\b(?:[1-9]\\d|kit|",
    guard: ["pnpm", "-s", "vitest", "run", "tests/quantity.test.ts"],
  },
  {
    id: "kit-conversa-nova",
    bug: "o kit abandonado voltava dias depois (nada fecha conversa; expira por tempo)",
    files: ["supabase/functions/turn/index.ts"],
    from: "(kitStale ? null : (lead.units as number | null))",
    to: "(lead.units as number | null)",
    guard: ["pnpm", "-s", "vitest", "run", "tests/function-drift.test.ts"],
  },
  {
    id: "kit-virgula",
    bug: "\"quero 2, M e G\" virava 1 peça (a vírgula depois do 2 não contava)",
    files: ["src/agent/interpret.ts"],
    from: "(?!\\\\d|[.,]\\\\d|",
    to: "(?![\\\\d,.]|",
    guard: ["pnpm", "-s", "vitest", "run", "tests/quantity.test.ts"],
  },
  {
    id: "kit-outra-pessoa",
    bug: "\"pra mim tá bom, e pra ela G\" trocava o tamanho dela pelo da outra",
    files: ["src/agent/interpret.ts"],
    from: "if (i.size.for_other_person || OTHER_PERSON.test(t)) return false;",
    to: "if (i.size.for_other_person) return false;",
    guard: ["pnpm", "-s", "vitest", "run", "tests/quantity.test.ts"],
  },
  {
    id: "kit-do-que",
    bug: "\"menos do que R$ 272,79\" passava como comparação (preço falso sozinho)",
    files: ["src/agent/guardrails.ts"],
    from: "moneys.slice(0, k).some(",
    to: "true || moneys.slice(0, k).some(",
    guard: ["pnpm", "-s", "vitest", "run", "tests/kits.test.ts"],
  },
  {
    id: "kit-oferta",
    bug: "\"Na entrega 2 peças ficam R$ 233,82, e uma sai R$ 129,90\" vetada (a peça avulsa não contava)",
    files: ["src/agent/guardrails.ts"],
    from: "counts.push({ at: u.index ?? 0, units: 1 });",
    to: "void u;",
    guard: ["pnpm", "-s", "vitest", "run", "tests/kits.test.ts"],
  },

  {
    id: "cep-entrega",
    bug: "\"dá pra ver a entrega em casa nesse tempo\" passava como pedido de CEP",
    files: ["src/agent/guardrails.ts"],
    from: "\\b(?:cep|endereco)\\b[^.!?]{0,20}?",
    to: "",
    guard: ["pnpm", "-s", "vitest", "run", "tests/prepaid-deadline-fuzz.test.ts"],
  },
  {
    id: "kit-sem-palavra",
    bug: "\"na entrega sai com 30% levando 3 peças\" passava (percentual sem a palavra desconto)",
    files: ["src/agent/guardrails.ts"],
    from: "!looksLikeDiscount(sentence, at) && !offers.some((o) => o.pct === value)",
    to: "!looksLikeDiscount(sentence, at)",
    guard: ["pnpm", "-s", "vitest", "run", "tests/kits.test.ts"],
  },
  {
    id: "kit-quatro",
    bug: "\"na entrega 4 peças saem R$ 311,76\" passava (quantidade sem kit)",
    files: ["src/agent/guardrails.ts"],
    from: "const N = \"(\\\\d|um|uma|dois|duas|tres|quatro|cinco)\";",
    to: "const N = \"(\\\\d|um|uma|dois|duas|tres|quatro|cinco)\"; if (sentence.includes(\"4\")) continue;",
    guard: ["pnpm", "-s", "vitest", "run", "tests/kits.test.ts"],
  },
  {
    id: "kit-renova",
    bug: "o kit ativo expirava no meio da conversa (o relógio só andava quando o kit mudava)",
    files: ["supabase/functions/turn/index.ts"],
    from: "  if (quantity || units > 1) {\n    await db(`leads?id=eq.${lead.id}`, {",
    to: "  if (quantity) {\n    await db(`leads?id=eq.${lead.id}`, {",
    guard: ["pnpm", "-s", "vitest", "run", "tests/function-drift.test.ts"],
  },
  {
    id: "kit-colete",
    bug: "\"eu uso G, ele é folgado?\" era lido como tamanho de outra pessoa",
    files: ["src/agent/interpret.ts"],
    from: "/\\b(?:dela|delas|",
    to: "/\\b(?:ela|ele|dela|delas|",
    guard: ["pnpm", "-s", "vitest", "run", "tests/quantity.test.ts"],
  },
  {
    id: "kit-pra-mim-e-pra",
    bug: "\"pra mim e pra minha irmã\" virava 1 peça",
    files: ["src/agent/interpret.ts"],
    from: "|\\b(?:pra|para)\\s+mim\\s+e\\s+(?:pra|para)\\s+",
    to: "",
    guard: ["pnpm", "-s", "vitest", "run", "tests/quantity.test.ts"],
  },
  {
    id: "caminho-escolhido",
    bug: 'o turno depois de "quero no pix" voltava para o link da entrega (a escolha valia só na mensagem)',
    files: ["supabase/functions/turn/index.ts"],
    from: "const linkPath = linkPathFor(paymentChoice, region);",
    to: "const linkPath = linkPathFor(interpretation.payment_choice, region);",
    guard: ["pnpm", "-s", "vitest", "run", "tests/function-drift.test.ts"],
  },
  {
    id: "gate-quantidade-da-conversa",
    bug: "\"na entrega o colete sai R$ 233,82\" passava numa conversa de 1 peça (o gate não sabia a quantidade)",
    files: ["src/agent/guardrails.ts"],
    from: "[...counts.map((c) => c.units), ctx.units ?? 1]",
    to: "[...counts.map((c) => c.units), 1, 2, 3]",
    guard: ["pnpm", "-s", "vitest", "run", "tests/kits.test.ts"],
  },
  {
    id: "gate-oracao",
    bug: "\"R$ 129,90 levando 2 peças\" passava (o preço não respondia à contagem da própria oração)",
    files: ["src/agent/guardrails.ts"],
    from: "if (own.length > 0) return new Set(own);",
    to: "",
    guard: ["pnpm", "-s", "vitest", "run", "tests/kits.test.ts"],
  },
  {
    id: "gate-quantidade-no-turno",
    bug: "o turno não passava a quantidade de peças ao gate",
    files: ["supabase/functions/turn/index.ts"],
    from: "      // The pieces in play: a kit price needs the kit, a 1-piece price the single piece.\n      units,",
    to: "",
    guard: ["pnpm", "-s", "vitest", "run", "tests/function-drift.test.ts"],
  },
  {
    id: "caminho-pergunta",
    bug: "\"vou pagar no pix?\" gravava o caminho (uma pergunta lida como escolha)",
    files: ["src/agent/interpret.ts"],
    from: "&& !questionAfter;",
    to: ";",
    guard: ["pnpm", "-s", "vitest", "run", "tests/quantity.test.ts"],
  },
  {
    id: "regua-kit",
    bug: "a véspera de um kit mandava \"deixa R$ 129,90 separado\" (a régua não lia o pedido)",
    files: ["src/agent/followups.ts"],
    from: "const price = brl(ctx.amountBrl ?? ctx.config.prices.codBrl);",
    to: "const price = brl(ctx.config.prices.codBrl);",
    guard: ["pnpm", "-s", "vitest", "run", "tests/followups.test.ts"],
  },
  {
    id: "regua-pedido",
    bug: "o cron não buscava o pedido para a régua pós-compra",
    files: ["supabase/functions/turn/index.ts"],
    from: "...(order && Number(order.amount_brl) > 0 ? { amountBrl: Number(order.amount_brl) } : {}),",
    to: "",
    guard: ["pnpm", "-s", "vitest", "run", "tests/function-drift.test.ts"],
  },
  {
    id: "adiada-kit",
    bug: "a resposta adiada de um kit era regateada como 1 peça e perdida",
    files: ["supabase/functions/turn/index.ts"],
    from: "      paymentPath: touchPath,\n      units: touchUnits,",
    to: "      paymentPath: \"cod\",",
    guard: ["pnpm", "-s", "vitest", "run", "tests/function-drift.test.ts"],
  },
  {
    id: "kit-so-uma",
    bug: "\"Se levar só uma, fica R$ 129,90\" vetada num kit (só uma não contava)",
    files: ["src/agent/guardrails.ts"],
    from: "|\\bso\\s+uma\\b|\\buma\\s+so\\b|",
    to: "|",
    guard: ["pnpm", "-s", "vitest", "run", "tests/kits.test.ts"],
  },
  {
    id: "kit-oracao-anterior",
    bug: "\"Se levar só uma, fica R$ 233,82\" passava (a oração sem contagem não seguia a anterior)",
    files: ["src/agent/guardrails.ts"],
    from: "const before = counts.filter((c) => c.at < start).at(-1);",
    to: "const before = undefined as { units: number } | undefined;",
    guard: ["pnpm", "-s", "vitest", "run", "tests/kits.test.ts"],
  },
  {
    id: "caminho-depois",
    bug: "\"quero no pix, qual a chave?\" não guardava a escolha (a pergunta depois derrubava)",
    files: ["src/agent/interpret.ts"],
    from: "const upTo = t.slice(0, m.index + m[0].length);",
    to: "const upTo = t;",
    guard: ["pnpm", "-s", "vitest", "run", "tests/quantity.test.ts"],
  },
  {
    id: "regua-antecipado",
    bug: "pedido antecipado recebia \"deixa R$ separado\" na véspera",
    files: ["src/agent/followups.ts"],
    from: "(ctx.prepaid ? \"\" : `Deixa",
    to: "(false ? \"\" : `Deixa",
    guard: ["pnpm", "-s", "vitest", "run", "tests/followups.test.ts"],
  },
  {
    id: "regua-total-do-pedido",
    bug: "a véspera era cancelada quando o total do pedido não era um preço do config",
    files: ["src/agent/guardrails.ts"],
    from: "if (orderAmount !== undefined) allowedPrices.add(orderAmount);",
    to: "",
    guard: ["pnpm", "-s", "vitest", "run", "tests/kits.test.ts"],
  },
  {
    id: "caminho-duvida",
    bug: "\"quero saber se aceita pix\" gravava o caminho",
    files: ["src/agent/interpret.ts"],
    from: "/\\b(?:saber|ver|pensar|entender|perguntar)\\s+(?:se|sobre|como)\\b|",
    to: "/\\bNUNCA\\b|",
    guard: ["pnpm", "-s", "vitest", "run", "tests/quantity.test.ts"],
  },
  {
    id: "peca-gratis",
    bug: "\"a segunda sai de graça\" passava (concessão sem número)",
    files: ["src/agent/guardrails.ts"],
    from: "(?:de\\s+gra[cç]a|por\\s+nossa\\s+conta|gratis)\\b(?!\\s+(?:pra|para)\\s+(?:trocar|devolver))",
    to: "(?:NUNCA)\\b(?!\\s+(?:pra|para)\\s+(?:trocar|devolver))",
    guard: ["pnpm", "-s", "vitest", "run", "tests/kits.test.ts"],
  },
  {
    id: "segunda-feira",
    bug: "\"na segunda eu te mando o link\" contava 2 peças",
    files: ["src/agent/guardrails.ts"],
    from: "|\\b(?:com|levando)\\s+a\\s+(segunda|terceira)\\b(?!\\s*-?\\s*feira)",
    to: "|\\b(?:na|com|levando|a)\\s+(segunda|terceira)\\b",
    guard: ["pnpm", "-s", "vitest", "run", "tests/kits.test.ts"],
  },
  {
    id: "tchau-nome",
    bug: "\"tchau brigada\" virava o nome da cliente no link",
    files: ["src/agent/identity.ts"],
    from: "|tchau|tchauzinho|brigad[ao]|",
    to: "|",
    guard: ["pnpm", "-s", "vitest", "run", "tests/closing.test.ts"],
  },
  {
    id: "ja-finalizei",
    bug: "\"obrigada, já finalizei\" passava a compradora para uma pessoa",
    files: ["src/agent/interpret.ts"],
    from: "if (orderContext && i.post_sale && !reportsDone(message)) return \"post_sale\";",
    to: "if (orderContext && i.post_sale) return \"post_sale\";",
    guard: ["pnpm", "-s", "vitest", "run", "tests/closing.test.ts"],
  },
  {
    id: "despedida-link",
    bug: "a despedida depois do link reenviava o link",
    files: ["supabase/functions/turn/index.ts"],
    from: " && !(linkInChat && closesConversation(inbound.body ?? \"\"))",
    to: "",
    guard: ["pnpm", "-s", "vitest", "run", "tests/function-drift.test.ts"],
  },
  {
    id: "feliz-com-queixa",
    bug: "\"obrigada, mas veio o M\" contava como encerramento feliz (sem handoff)",
    files: ["src/agent/interpret.ts"],
    from: ".every((w) => DONE_WORDS.test(w));",
    to: ".every((w) => w.length > 0);",
    guard: ["pnpm", "-s", "vitest", "run", "tests/closing.test.ts"],
  },
  {
    id: "troca-e-segunda",
    bug: "\"a troca é grátis e a segunda peça também\" passava (peça grátis atrás da troca)",
    files: ["src/agent/guardrails.ts"],
    from: "|\\b(?:gratis|de\\s+gra[cç]a|por\\s+nossa\\s+conta)\\b[^.!?]{0,30}\\b(?:segund[oa]|outr[oa])\\s+(?:peca\\s+)?tambem\\b",
    to: "",
    guard: ["pnpm", "-s", "vitest", "run", "tests/kits.test.ts"],
  },
  {
    id: "prazo-por-caminho",
    bug: "\"na entrega 3 dias, e no antecipado 5 dias\" virava resposta pronta numa conversa do antecipado",
    files: ["src/agent/guardrails.ts"],
    from: 'let near: Path | null = codAt > prepayAt ? "cod" : prepayAt > codAt ? "prepay" : null;',
    to: 'let near: Path | null = prepayAt > codAt ? "prepay" : null;',
    guard: ["pnpm", "-s", "vitest", "run", "tests/prepaid-deadline-fuzz.test.ts"],
  },
  {
    id: "o-g-dela",
    bug: "\"e o G dela\" não era lido como tamanho dito (o placar contava troca)",
    files: ["src/agent/sizing.ts"],
    from: "|o\\s+(?=(?:pp|p|m|gg|g|xgg|eg)\\s+(?:dela|dele|mesmo)\\b)",
    to: "",
    guard: ["pnpm", "-s", "vitest", "run", "tests/sizing.test.ts"],
  },
  {
    id: "O10-venda",
    bug: "o webhook de venda aceitava venda forjada sem a senha",
    files: ["supabase/functions/turn/index.ts"],
    from: 'if (saleToken !== "" && !sameSecret(String(payload.token ?? ""), saleToken)) {',
    to: "if (false) {",
    guard: ["pnpm", "-s", "vitest", "run", "tests/function-drift.test.ts"],
  },
  {
    id: "O2-wait",
    bug: "lead novo recebia a recepção e nunca mais era respondido (sem o nó Wait)",
    files: ["n8n/workflows/turno-da-agente.json"],
    from: '"type": "n8n-nodes-base.wait"',
    to: '"type": "n8n-nodes-base.noOp"',
    guard: ["pnpm", "-s", "vitest", "run", "tests/n8n-workflows.test.ts"],
  },
  // Revisão de integração (2026-09-27): "um/uma" como artigo, a negação que governa a contagem,
  // e o nome do antecipado negado por "não precisa <verbo>" / "nem no <nome>".
  {
    id: "um-dia-bom",
    bug: "o silence_1 \"esperando um dia bom\" era vetado no antecipado e a varredura cancelava o toque em silêncio",
    files: ["src/agent/guardrails.ts"],
    from: "          /^n?uma?$/.test(m[1]!) &&\n          !talksDelivery(sentence) &&",
    to: "          false &&\n          !talksDelivery(sentence) &&",
    // 2026-09-28: the prepaid fallback now needs delivery talk too, so the bug is both layers.
    also: [{ from: "(!named && ctx.paymentPath === \"prepay\" && (deadlineTalk || averageWord))", to: "(!named && ctx.paymentPath === \"prepay\")" }],
    guard: ["pnpm", "-s", "vitest", "run", "tests/followups.test.ts"],
  },
  {
    id: "um-artigo-largo",
    bug: "exigir só palavra de entrega para \"um/uma\" soltava \"em uma semana o colete é seu\" no antecipado",
    files: ["src/agent/guardrails.ts"],
    from: String.raw`            (!/\b(?:em|de|ate|dentro\s+de|por|media|cerca|so|apenas|tem|tera|sao|e|fica|leva\w*|demor\w*|dura\w*|passa\w*|mais|menos|que)\s+$/.test(before) &&`,
    to: "            (true &&",
    // 2026-09-28: the one ARRIVAL has her having it, so the verb-only list is the other half of the bug.
    also: [
      {
        from: "          !talksDelivery(sentence) &&\n          !bare &&",
        to: String.raw`          !/\b(?:prazo|cheg\w*|entreg\w*|receb\w*|lev[ae]\w*|demor\w*|envi\w*|despach\w*|post\w*)\b/.test(sentence) &&
          !bare &&`,
      },
    ],
    guard: ["pnpm", "-s", "vitest", "run", "tests/prepaid-deadline-fuzz.test.ts"],
  },
  {
    id: "uma-semana-negada",
    bug: "\"na entrega não chega em uma semana, chega em 1 a 3 dias\" era vetada pela semana que ela nega",
    files: ["src/agent/guardrails.ts"],
    from: "          if (denied) continue;\n",
    to: "",
    also: [{ from: "        if (denied && !week && days < avg) continue;\n", to: "" }],
    guard: ["pnpm", "-s", "vitest", "run", "tests/prepaid-deadline-fuzz.test.ts"],
  },
  {
    id: "pix-nao-precisa-verbo",
    bug: "\"no pix não precisa esperar, chega em 2 dias\" lia o pix como negado e passava no COD",
    files: ["src/agent/guardrails.ts"],
    from: String.raw`/^\s*nao(?:\s+precisa)?\s*(?:[.!,;:?]|$)/.test(rest)`,
    to: String.raw`/^\s*nao\s*(?:[.!,;:?]|$|precisa\b)/.test(rest)`,
    guard: ["pnpm", "-s", "vitest", "run", "tests/prepaid-deadline-fuzz.test.ts"],
  },
  {
    id: "nem-no-pix",
    bug: "\"nem no pix demora, chega em 2 dias\" (nem = nem mesmo) lia o pix como negado e passava no COD",
    files: ["src/agent/guardrails.ts"],
    from: "          const closes =\n",
    to: "          const closes =\n            /^nem\\b/.test(denier?.[0] ?? \"\") ||\n",
    guard: ["pnpm", "-s", "vitest", "run", "tests/prepaid-deadline-fuzz.test.ts"],
  },
  // Reestruturação do delivery_promise (2026-09-28): um nome por caminho, uma função de caminho
  // (pathOf), um vocabulário de chegada — e os consertos a–g por cima dela.
  {
    id: "recusa-qualquer-contagem",
    bug: "\"na entrega não chega em 5 dias, chega em 1 a 3 dias\" era vetada: só \"um/uma\" negado contava como recusa",
    files: ["src/agent/guardrails.ts"],
    from: "        const denied =\n          /\\b(?:nao|nunca|jamais)",
    to: "        const denied =\n          /^n?uma?$/.test(m[1]!) &&\n          /\\b(?:nao|nunca|jamais)",
    guard: ["pnpm", "-s", "vitest", "run", "tests/prepaid-deadline-fuzz.test.ts"],
  },
  {
    id: "garantia-e-media",
    bug: "a fala da garantia com a média do antecipado na mesma frase (prompt.ts) era vetada nos dois caminhos",
    files: ["src/agent/guardrails.ts"],
    from: "            (newClause && PREPAY_ONE.test(tail) && onlyPrepayWindow(tail)) ||\n",
    to: "",
    guard: ["pnpm", "-s", "vitest", "run", "tests/prepaid-deadline-fuzz.test.ts"],
  },
  {
    id: "fallback-chegada",
    bug: "no antecipado toda contagem sem caminho era prazo: \"o reembolso cai em até 5 dias\", \"a promoção vale por 5 dias\" eram vetadas",
    files: ["src/agent/guardrails.ts"],
    from: "(!named && ctx.paymentPath === \"prepay\" && (deadlineTalk || averageWord))",
    to: "(!named && ctx.paymentPath === \"prepay\")",
    guard: ["pnpm", "-s", "vitest", "run", "tests/prepaid-deadline-fuzz.test.ts"],
  },
  {
    id: "resposta-nua",
    bug: "com o fallback exigindo chegada, \"É 2 dias.\" (a contagem como resposta inteira) passaria no antecipado",
    files: ["src/agent/guardrails.ts"],
    from: "        const deadlineTalk = talksDelivery(sentence) || bare;",
    to: "        const deadlineTalk = talksDelivery(sentence);",
    guard: ["pnpm", "-s", "vitest", "run", "tests/prepaid-deadline-fuzz.test.ts"],
  },
  {
    id: "cauda-garantia",
    bug: "\"7 dias pra trocar e suporte todo dia / sem perder tempo / mesmo tamanho ou outro\" eram vetadas pela palavra de tempo que só dividem",
    files: ["src/agent/guardrails.ts"],
    from: String.raw`                tail.replace(/\btod[oa]s?\s+(?:o\s+|os\s+)?dias?\b|\bperder\s+tempo\b|\bmesm[oa]\s+(?:tamanho|numero|modelo|cor)\b/g, " "),`,
    to: "                tail,",
    guard: ["pnpm", "-s", "vitest", "run", "tests/prepaid-deadline-fuzz.test.ts"],
  },
  {
    id: "nega-adjetivo",
    bug: "\"Nada de pix demorado: chega em 2 dias\" lia o pix como negado e passava no COD",
    files: ["src/agent/guardrails.ts"],
    from: "          const closes =\n",
    to: "          const closes =\n            !/^nem\\b/.test(denier?.[0] ?? \"\") ||\n",
    guard: ["pnpm", "-s", "vitest", "run", "tests/prepaid-deadline-fuzz.test.ts"],
  },
  {
    id: "caminho-depois",
    bug: "\"Chega em 2 dias no pix.\" passava no COD e \"Chega em 5 dias na entrega.\" no antecipado: a contagem só lia o nome antes dela",
    files: ["src/agent/guardrails.ts"],
    from: "        const prepayAny = prepaidNamed(sentence) !== -1;\n        const codAny = names(COD_NAME, sentence);",
    to: "        const prepayAny = prepaidNamed(head) !== -1;\n        const codAny = names(COD_NAME, head);",
    also: [
      { from: "        if (near == null && prepaidNamed(ownAfter) !== -1) near = \"prepay\";\n", to: "" },
      { from: "        if (near == null && names(COD_NAME, ownAfter) && prepaidNamed(ownAfter) === -1) {", to: "        if (false) {" },
    ],
    guard: ["pnpm", "-s", "vitest", "run", "tests/prepaid-deadline-fuzz.test.ts"],
  },
  {
    id: "os-dois-caminhos",
    bug: "\"Na entrega ou no pix, em média 5 dias úteis\" passava no COD: o caminho mais perto levava a contagem sozinho",
    files: ["src/agent/guardrails.ts"],
    from: "return { path: codAny && equatedIn(sentence) ? \"both\" : \"prepay\", by: \"name\" };",
    to: "return { path: \"prepay\", by: \"name\" };",
    also: [{ from: "deliveryKeeps(sentence, head, tail, codAt) ? \"cod\" : \"both\", by };", to: "deliveryKeeps(sentence, head, tail, codAt) ? \"cod\" : \"prepay\", by };" }],
    guard: ["pnpm", "-s", "vitest", "run", "tests/prepaid-deadline-fuzz.test.ts"],
  },
  {
    id: "cabecalho-entrega-no-antecipado",
    bug: "\"Vai ser na entrega? Chega em média 5 dias úteis.\" passava no antecipado: o cabeçalho da entrega só valia no COD",
    files: ["src/agent/guardrails.ts"],
    from: "((ctx.paymentPath === \"cod\" || path === \"cod\") && path !== \"prepay\"",
    to: "(ctx.paymentPath === \"cod\" && path !== \"prepay\"",
    guard: ["pnpm", "-s", "vitest", "run", "tests/prepaid-deadline-fuzz.test.ts"],
  },
  {
    id: "entregador-nome",
    bug: "\"O entregador leva 2 dias.\" passava no antecipado: o entregador (dos dois caminhos) nomeava a entrega",
    files: ["src/agent/guardrails.ts"],
    from: "const COD_NAME = /\\bna\\s+entrega\\b|",
    to: "const COD_NAME = /\\bentregador\\b|\\bna\\s+entrega\\b|",
    guard: ["pnpm", "-s", "vitest", "run", "tests/prepaid-deadline-fuzz.test.ts"],
  },
  {
    id: "cauda-de-preco",
    bug: "a faixa da entrega com o antecipado depois aceitaria tempo junto do preço (\"…, e com desconto chega antes\")",
    files: ["src/agent/guardrails.ts"],
    from: String.raw`                !talksDelivery(c.replace(COD_NAME, " ")) &&`,
    to: "                true &&",
    also: [{ from: String.raw`                !/\b(?:dias?|semanas?|horas?|tempo|junto|parecid\w*|similar\w*|diferen\w*|bate\w*|rapid\w*|logo)\b/.test(c)),`, to: "                true)," }],
    guard: ["pnpm", "-s", "vitest", "run", "tests/prepaid-deadline-fuzz.test.ts"],
  },
  {
    id: "R2-link-janela",
    bug: "o turno depois do link armava before_size (que tamanho você usa?)",
    files: ["supabase/functions/turn/index.ts"],
    from: "if (linkSentRecently([...earlier, replyText], CHECKOUT_BASES)) return \"link_sent\";",
    to: "if (linkSentRecently([replyText], CHECKOUT_BASES)) return \"link_sent\";",
    guard: ["pnpm", "-s", "vitest", "run", "tests/order-stage.test.ts"],
  },
  {
    id: "R2-lembrete-so-no-link",
    bug: "cada turno depois do link rearmava o lembrete de 15 min",
    files: ["src/agent/followups.ts", "supabase/functions/turn/followups.ts"],
    from: "(f) => f.kind !== \"checkout_reminder\" || postponed !== undefined || linkInReply,",
    to: "(_f) => true,",
    guard: ["pnpm", "-s", "vitest", "run", "tests/followups.test.ts"],
  },
  {
    id: "R2-lembrete-turno",
    bug: "o turno armava o lembrete pelo ponto de parada, não pelo link desta resposta",
    files: ["supabase/functions/turn/index.ts"],
    from: "    stopPointOf(replyText, recentOutbound),\n    linkSentRecently([replyText], CHECKOUT_BASES),\n",
    to: "    stopPointOf(replyText, recentOutbound),\n    stopPointOf(replyText, recentOutbound) === \"link_sent\",\n",
    guard: ["pnpm", "-s", "vitest", "run", "tests/order-stage.test.ts"],
  },
  {
    id: "R2-regua-recomeca",
    bug: "silence_2/silence_3 adiado rearmava os toques já enviados",
    files: ["src/agent/followups.ts", "supabase/functions/turn/followups.ts"],
    from: "  const at = ruler.findIndex((f) => f.kind === postponed);",
    to: "  const at = ruler.findIndex((f) => f.kind === postponed && f.kind !== \"silence_2\" && f.kind !== \"silence_3\");",
    guard: ["pnpm", "-s", "vitest", "run", "tests/followups.test.ts"],
  },
  {
    id: "R2-adiamento-posse",
    bug: "o adiamento reancorava a régua que o turno dela acabou de armar",
    files: ["supabase/functions/turn/index.ts"],
    from: "        if (!Array.isArray(moved) || moved.length === 0) {\n          skipped.push({ followupId: row.id, reason: \"ela respondeu antes do adiamento\" });\n          return;\n        }\n",
    to: "",
    guard: ["pnpm", "-s", "vitest", "run", "tests/order-stage.test.ts"],
  },
  {
    id: "R2-dois-pedidos-vivo",
    bug: "A e B criados, A cancelado: B ficava sem véspera",
    files: ["src/agent/followups.ts", "supabase/functions/turn/followups.ts"],
    from: "const live = isOrderDead(order.status) ? others.find((o) => !isOrderDead(o.status)) : order;",
    to: "const live = isOrderDead(order.status) ? undefined : order;",
    guard: ["pnpm", "-s", "vitest", "run", "tests/followups.test.ts"],
  },
  {
    id: "R2-mesmo-pedido-nao-herda",
    bug: "webhook atrasado do mesmo pedido cancelado rearmava os toques dele",
    files: ["src/agent/followups.ts", "supabase/functions/turn/followups.ts"],
    from: "existing.some((e) => e.kind === f.kind && e.status !== \"sent\" && !!e.orderId && dead.includes(e.orderId)),",
    to: "existing.some((e) => e.kind === f.kind && e.status !== \"sent\"),",
    guard: ["pnpm", "-s", "vitest", "run", "tests/followups.test.ts"],
  },
  {
    id: "R2-recusado-reabre",
    bug: "pedido novo depois de um recusado ficava recusado",
    files: ["src/agent/followups.ts", "supabase/functions/turn/followups.ts"],
    from: "!isOrderDead(status) && others.some((s) => isOrderDead(s));",
    to: "false;",
    guard: ["pnpm", "-s", "vitest", "run", "tests/followups.test.ts"],
  },
  {
    id: "R2-retry-janela-posse",
    bug: "nova tentativa fora da janela virava handoff mesmo com a linha cancelada pela mensagem nova dela",
    files: ["supabase/functions/turn/index.ts"],
    from: "        const closed = await mark(\"canceled\");\n        if (!Array.isArray(closed) || closed.length === 0) {\n          skipped.push({ followupId: row.id, reason: \"ela escreveu de novo antes da nova tentativa\" });\n          return;\n        }\n",
    to: "        await mark(\"canceled\");\n",
    guard: ["pnpm", "-s", "vitest", "run", "tests/order-stage.test.ts"],
  },
  {
    id: "R2-externalid-malformado",
    bug: "externalId com surrogate isolado estourava URIError depois do upsert",
    files: ["supabase/functions/turn/index.ts"],
    from: "  if (!order.externalId.isWellFormed()) return { status: \"external_id_malformed\", ok: false };\n",
    to: "",
    guard: ["pnpm", "-s", "vitest", "run", "tests/order-stage.test.ts"],
  },
  {
    id: "R2-varredura-isolada",
    bug: "uma linha que lançava derrubava a varredura e sumia com os toques já fechados",
    files: ["supabase/functions/turn/index.ts"],
    from: "    await sweepRow(row).catch((error) => {\n      skipped.push({\n        followupId: row.id,\n        reason: `erro: ${redactKeys(error instanceof Error ? error.message : String(error))}`,\n      });\n    });\n",
    to: "    await sweepRow(row);\n",
    guard: ["pnpm", "-s", "vitest", "run", "tests/order-stage.test.ts"],
  },
  {
    id: "PEDIDO-morto-ressuscita",
    bug: "\"created\" ou \"Enviado\" atrasado depois do \"Cancelado\" ressuscitava o pedido e dava a régua inteira a um cancelado",
    files: ["src/agent/followups.ts", "supabase/functions/turn/followups.ts"],
    from: "  isOrderDead(stored ?? undefined) && !isOrderDead(incoming) ? stored! : incoming;",
    to: "  incoming;",
    guard: ["pnpm", "-s", "vitest", "run", "tests/order-stage.test.ts"],
  },
  {
    id: "PEDIDO-grava-status-do-webhook",
    bug: "recordOrder gravava em orders.status o status do webhook que chegou por último, não o efetivo",
    files: ["supabase/functions/turn/index.ts"],
    from: "      amount_brl: order.amountBrl,\n      status,\n",
    to: "      amount_brl: order.amountBrl,\n      status: order.status ?? \"created\",\n",
    guard: ["pnpm", "-s", "vitest", "run", "tests/order-stage.test.ts"],
  },
  {
    id: "PEDIDO-data-da-chegada",
    bug: "created_at do pedido era a chegada do primeiro webhook: o takeover agendava a véspera do vivo pela data errada",
    files: ["supabase/functions/turn/index.ts"],
    from: "      ...(orderedOn && !Number.isNaN(orderedOn.getTime()) ? { created_at: orderedOn.toISOString() } : {}),\n",
    to: "",
    guard: ["pnpm", "-s", "vitest", "run", "tests/order-stage.test.ts"],
  },
  {
    id: "TPL-antecipado-cobra",
    bug: "a véspera do antecipado fora da janela saía pelo template que diz \"Deixa R$ X separado\" a quem já pagou",
    files: ["src/agent/followups.ts", "supabase/functions/turn/followups.ts"],
    from: "templates?.[kind === \"order_eve\" && ctx.prepaid ? \"order_eve_pago\" : kind];",
    to: "templates?.[kind];",
    guard: ["pnpm", "-s", "vitest", "run", "tests/whatsapp-templates.test.ts"],
  },
  {
    id: "TPL-segunda-variante",
    bug: "fora da janela o template mandava a 1ª variante do silence_2 e o gate lia a 2ª, a que metade dos leads nunca recebe",
    files: ["src/agent/followups.ts", "supabase/functions/turn/followups.ts"],
    from: "    body: kind === \"silence_2\" ? SILENCE_2(ctx.config.delivery.warrantyDays)[0] : body,\n",
    to: "    body,\n",
    guard: ["pnpm", "-s", "vitest", "run", "tests/whatsapp-templates.test.ts"],
  },
  {
    id: "OPTIN-marketing-sem-consentimento",
    bug: "silence_2/silence_3 saíam como template MARKETING fora da janela para quem nunca consentiu",
    files: ["src/agent/followups.ts", "supabase/functions/turn/followups.ts"],
    from: "  if ((kind === \"silence_2\" || kind === \"silence_3\") && ctx.marketingOptIn !== true) {\n    return { via: \"blocked\", reason: \"no_opt_in\" };\n  }\n",
    to: "",
    guard: ["pnpm", "-s", "vitest", "run", "tests/followups.test.ts"],
  },
  {
    id: "OPTIN-gate-le-outra-variante",
    bug: "a varredura passava no gate o texto livre (renderFollowup), não o corpo do template que de fato sai",
    files: ["supabase/functions/turn/index.ts"],
    from: "const text = delivery !== null && delivery.via !== \"blocked\" ? delivery.body : renderFollowup(kind, renderCtx);",
    to: "const text = renderFollowup(kind, renderCtx);",
    guard: ["pnpm", "-s", "vitest", "run", "tests/opt-in.test.ts"],
  },
  {
    id: "OPTIN-flag-ausente-liga",
    bug: "askMarketingOptIn ausente no secret ligava o opt-in e a varredura lia colunas da 0019",
    files: ["supabase/functions/turn/index.ts"],
    from: "const ASK_OPT_IN = CONFIG.channel?.askMarketingOptIn === true;",
    to: "const ASK_OPT_IN = CONFIG.channel?.askMarketingOptIn !== false;",
    guard: ["pnpm", "-s", "vitest", "run", "tests/opt-in.test.ts"],
  },
  {
    id: "OPTIN-selo-sem-toque",
    bug: "o id do botão ficava fora do selo: qualquer um trocava \"optin:no\" por \"optin:yes\" e forjava o consentimento",
    files: ["src/channel/inbound-signature.ts", "supabase/functions/turn/inbound-signature.ts", "supabase/functions/whatsapp/inbound-signature.ts"],
    from: "m.sentAt ?? \"\", ...(m.reply ? [m.reply.id] : [])];",
    to: "m.sentAt ?? \"\"];",
    guard: ["pnpm", "-s", "vitest", "run", "tests/whatsapp-channel.test.ts"],
  },
  {
    id: "OPTIN-turno-ignora-toque-no-selo",
    bug: "o turno conferia o selo sem o reply: todo toque de botão voltava 401 com o selo ligado",
    files: ["supabase/functions/turn/index.ts"],
    from: "sentAt: payload.sentAt, reply: payload.reply }",
    to: "sentAt: payload.sentAt }",
    also: [{ from: "sentAt: payload.sentAt, reply: payload.reply }", to: "sentAt: payload.sentAt }" }],
    guard: ["pnpm", "-s", "vitest", "run", "tests/opt-in.test.ts"],
  },
  {
    id: "OPTIN-suspensao-sem-flag",
    bug: "com a flag desligada e sem consentimento, o texto dela gravava marketing_opt_in_suspended_at (coluna da 0019)",
    files: ["supabase/functions/turn/index.ts"],
    from: "(ASK_OPT_IN || lead.marketing_opt_in_at) && suspendsMarketingOptIn(",
    to: "suspendsMarketingOptIn(",
    guard: ["pnpm", "-s", "vitest", "run", "tests/opt-in.test.ts"],
  },
  {
    id: "WA-selo-reply-n8n",
    bug: "o nó \"Cerebro do turno\" montava o corpo sem o reply selado: 401 em todo toque de botão",
    files: ["n8n/workflows/turno-da-agente.json"],
    from: "signature: $json.body.signature, reply: $json.body.reply })",
    to: "signature: $json.body.signature })",
    guard: ["pnpm", "-s", "vitest", "run", "tests/n8n-workflows.test.ts"],
  },
  {
    id: "WA-selo-reply-resume",
    bug: "a retomada do turno (\"Resposta de verdade\") reenviava sem o reply selado: 401 no toque que caiu na recepção",
    files: ["n8n/workflows/turno-da-agente.json"],
    from: "signature: $('Mensagem recebida').first().json.body.signature, reply: $('Mensagem recebida').first().json.body.reply, resume: true",
    to: "signature: $('Mensagem recebida').first().json.body.signature, resume: true",
    guard: ["pnpm", "-s", "vitest", "run", "tests/n8n-workflows.test.ts"],
  },
  {
    id: "WA-131050",
    bug: "o erro 131050 (ela desligou marketing) não virava recusa: o template seguia saindo e voltando",
    files: ["src/channel/whatsapp.ts", "supabase/functions/whatsapp/whatsapp.ts"],
    from: "    ...deliveryErrors(payload, phoneNumberId).filter((e) => e.code === 131050 && e.to).map((e) => e.to),\n",
    to: "",
    guard: ["pnpm", "-s", "vitest", "run", "tests/whatsapp-channel.test.ts"],
  },
  {
    id: "WA-prefs-stop",
    bug: "o stop em \"Ofertas e novidades\" do WhatsApp (user_preferences) não virava recusa",
    files: ["src/channel/whatsapp.ts", "supabase/functions/whatsapp/whatsapp.ts"],
    from: "    ...marketingPreferences(payload, phoneNumberId).filter((p) => p.value === \"stop\").map((p) => p.from),\n",
    to: "",
    guard: ["pnpm", "-s", "vitest", "run", "tests/whatsapp-channel.test.ts"],
  },
  {
    id: "WA-131050-digitos",
    bug: "o recipient_id do 131050 com + ou espaço não casava com leads.phone e a recusa não gravava",
    files: ["src/channel/whatsapp.ts", "supabase/functions/whatsapp/whatsapp.ts"],
    from: "to: str(st?.recipient_id).replace(/\\D/g, \"\")",
    to: "to: str(st?.recipient_id)",
    guard: ["pnpm", "-s", "vitest", "run", "tests/whatsapp-channel.test.ts"],
  },
  {
    id: "pos-compra-regua",
    bug: "quem já comprou e escrevia de novo voltava a receber a régua de silêncio (cupom, \"que tamanho você usa?\")",
    files: ["src/agent/followups.ts", "supabase/functions/turn/followups.ts"],
    from: "![\"pedido_criado\", \"em_rota\", \"entregue_pago\"].includes(stage ?? \"\") && orderStatuses.every((s) => isOrderDead(s));",
    to: "true;",
    guard: ["pnpm", "-s", "vitest", "run", "tests/order-stage.test.ts"],
  },
  {
    id: "pos-compra-agendamento",
    bug: "o agendamento da régua de silêncio não olhava o pedido vivo",
    files: ["supabase/functions/turn/index.ts"],
    from: "  if (at && !chasesSilence(",
    to: "  if (false && !chasesSilence(",
    guard: ["pnpm", "-s", "vitest", "run", "tests/order-stage.test.ts"],
  },
  {
    id: "pos-compra-varredura",
    bug: "a varredura mandava toque de silêncio a quem tem pedido vivo",
    files: ["supabase/functions/turn/index.ts"],
    from: "    if (inSilenceRuler(row.kind) && !chasesSilence(",
    to: "    if (false && !chasesSilence(",
    guard: ["pnpm", "-s", "vitest", "run", "tests/order-stage.test.ts"],
  },
  {
    id: "vespera-entregue",
    bug: "a véspera saía depois de \"Entregue\": o pedido entregue só cancelava o silêncio",
    files: ["src/agent/followups.ts", "supabase/functions/turn/followups.ts"],
    from: "  if (stageForOrder(status) === \"entregue_pago\") {",
    to: "  if (false) {",
    guard: ["pnpm", "-s", "vitest", "run", "tests/followups.test.ts"],
  },
  {
    id: "vespera-entregue-herda",
    bug: "o pedido vivo herdava a véspera mesmo já entregue",
    files: ["src/agent/followups.ts", "supabase/functions/turn/followups.ts"],
    from: "      orderTouchDue(f.kind, live.status) &&\n",
    to: "",
    guard: ["pnpm", "-s", "vitest", "run", "tests/followups.test.ts"],
  },
  {
    id: "vespera-entregue-varredura",
    bug: "a varredura mandava toque de pedido sem ler o status do pedido",
    files: ["supabase/functions/turn/index.ts"],
    from: "    if (order && !orderTouchDue(kind, order.status ?? undefined)) {",
    to: "    if (false) {",
    guard: ["pnpm", "-s", "vitest", "run", "tests/order-stage.test.ts"],
  },
  {
    id: "recusado-primeiro",
    bug: "\"Cancelado\" chegando primeiro deixava o estágio em endereco_coletado/perdido",
    files: ["src/agent/state-machine.ts", "supabase/functions/turn/state-machine.ts"],
    from: "const from = reached === \"recusado\" ? furthest(stored, \"pedido_criado\") : stored;",
    to: "const from = stored;",
    guard: ["pnpm", "-s", "vitest", "run", "tests/state-machine.test.ts"],
  },
  {
    id: "WA-recusa-gravada",
    bug: "a recusa de marketing (131050, user_preferences stop) era lida e nunca gravada",
    files: ["supabase/functions/whatsapp/index.ts"],
    from: "marketingDeclines(payload, PHONE_NUMBER_ID).map(declineMarketing)",
    to: "[] as string[]",
    guard: ["pnpm", "-s", "vitest", "run", "tests/whatsapp-channel.test.ts"],
  },
  {
    id: "R3-negacao-nomeia",
    bug: "\"Sem pix, em 5 dias você tem o colete\" passava: o nome negado não nomeava a entrega",
    files: ["src/agent/guardrails.ts"],
    from: "deadlineTalk || by === \"denial\"))) {",
    to: "deadlineTalk))) {",
    guard: ["pnpm", "-s", "vitest", "run", "tests/prepaid-deadline-fuzz.test.ts"],
  },
  {
    id: "R3-negacao-artigo",
    bug: "\"Sem pix, numa semana você está usando ele\" passava pela exceção do artigo",
    files: ["src/agent/guardrails.ts"],
    from: "              !deniesPrepaid(sentence) &&\n",
    to: "",
    guard: ["pnpm", "-s", "vitest", "run", "tests/prepaid-deadline-fuzz.test.ts"],
  },
  {
    id: "R3-posse-ter",
    bug: "\"você tem o colete\" não era chegada",
    files: ["src/agent/guardrails.ts"],
    from: "ja\\s+tem|(?:tem|tera|vai\\s+ter)\\s+(?:o\\s+(?:seu\\s+)?colete|ele)|",
    to: "ja\\s+tem|",
    guard: ["pnpm", "-s", "vitest", "run", "tests/prepaid-deadline-fuzz.test.ts"],
  },
  {
    id: "R3-janela-da-entrega",
    bug: "\"7 dias pra devolver, e a entrega leva de 1 a 3 dias\" era vetada: a janela vizinha virava prazo do 7",
    files: ["src/agent/guardrails.ts"],
    from: "            (newClause && codWindow.test(tail)) ||\n",
    to: "",
    guard: ["pnpm", "-s", "vitest", "run", "tests/prepaid-deadline-fuzz.test.ts"],
  },
  {
    id: "R3-media-sujeito",
    bug: "\"a média do antecipado é de 5 dias, tá?\" depois da garantia dava o 7 ao antecipado",
    files: ["src/agent/guardrails.ts"],
    from: ".replace(/\\b(?:a\\s+)?media\\s+(?:(?:d[oa]|n[oa])\\s+)?(?:e|fica|sao)\\s+(?:de\\s+)?\\d{1,2}(?:[.,]\\d)?\\s*dias?(?:\\s+uteis)?/g, \"\")",
    to: "",
    guard: ["pnpm", "-s", "vitest", "run", "tests/prepaid-deadline-fuzz.test.ts"],
  },
  {
    id: "R3-garantia-da-media",
    bug: "a warranty_promise lia a média do antecipado como garantia de 5 dias",
    files: ["src/agent/guardrails.ts"],
    from: "if (/\\bmedia\\b/.test(own) && ",
    to: "if (false && /\\bmedia\\b/.test(own) && ",
    guard: ["pnpm", "-s", "vitest", "run", "tests/prepaid-deadline-fuzz.test.ts"],
  },
  {
    id: "R3-teto",
    bug: "resposta degenerada de 16 mil caracteres levava 7 a 8 s no gate",
    files: ["src/agent/guardrails.ts"],
    from: "if (counted > 20) return",
    to: "if (counted > 1e9) return",
    also: [{ from: "some((s) => s.length > 1000))", to: "some((s) => s.length > 1e9))" }],
    guard: ["pnpm", "-s", "vitest", "run", "tests/prepaid-deadline-fuzz.test.ts"],
  },
  {
    id: "R3-cabecalho-corrida",
    bug: "a memoização do cabeçalho perdia o caminho nomeado atrás",
    files: ["src/agent/guardrails.ts"],
    from: "                    : (walk.at(-1) ?? null),",
    to: "                    : null,",
    guard: ["pnpm", "-s", "vitest", "run", "tests/prepaid-deadline-fuzz.test.ts"],
  },
  {
    id: "R3-opt-out-formas",
    bug: "\"não quero receber mais mensagens\", \"chega de mensagem\", \"para com isso\" não eram opt-out",
    files: ["src/agent/guardrails.ts"],
    from: "    ).test(t) &&\n    t.split(/[^a-z0-9]+/).every(",
    to: "    ).test(\"\") &&\n    t.split(/[^a-z0-9]+/).every(",
    guard: ["pnpm", "-s", "vitest", "run", "tests/opt-out-gaps.test.ts"],
  },
  {
    id: "R3-opt-out-compra",
    bug: "\"chega de mensagem, quero fechar\" virava opt-out e perdia a venda",
    files: ["src/agent/guardrails.ts"],
    from: "t.split(/[^a-z0-9]+/).every((w) => w === \"\" || REFUSAL_ONLY.test(w))",
    to: "true",
    guard: ["pnpm", "-s", "vitest", "run", "tests/opt-out-gaps.test.ts"],
  },
  {
    id: "R3-opt-out-nao-para",
    bug: "\"não para de mandar oferta boa não\" era lido como opt-out explícito",
    files: ["src/agent/guardrails.ts"],
    from: "/(?<!\\bnao\\s+)\\b(para|pare|parem|pode\\s+parar)",
    to: "/(para|pare|parem|pode\\s+parar)",
    guard: ["pnpm", "-s", "vitest", "run", "tests/opt-out-gaps.test.ts"],
  },
  {
    id: "R15.3-ausente-veta",
    bug: "a chave ausente no secret vetava o frete grátis da entrega",
    files: ["src/agent/guardrails.ts"],
    from: "const codFree = ctx.config.delivery.codFreeShipping !== false;",
    to: "const codFree = ctx.config.delivery.codFreeShipping === true;",
    guard: ["pnpm", "-s", "vitest", "run", "tests/honest-sales-lines.test.ts"],
  },
  {
    id: "R15.3-prompt-le-diferente",
    bug: "o prompt lia a chave do frete da entrega diferente do gate",
    files: ["src/agent/prompt.ts"],
    from: "    : config.delivery.codFreeShipping !== false",
    to: "    : config.delivery.codFreeShipping === true",
    guard: ["pnpm", "-s", "vitest", "run", "tests/prompt.test.ts"],
  },
  {
    id: "R15.3-seco-no-cod",
    bug: "\"frete grátis\" sem caminho passava porque o turno manda \"cod\" sempre",
    files: ["src/agent/guardrails.ts"],
    from: "            if (codFree && canonical.test(canonicalShape(sentence))) {",
    to: "            if (codFree && (ctx.paymentPath === \"cod\" || canonical.test(canonicalShape(sentence)))) {",
    guard: ["pnpm", "-s", "vitest", "run", "tests/honest-sales-lines.test.ts"],
  },
  {
    id: "R15.3-negacao-honesta",
    bug: "\"No pix não tem frete grátis\" (a verdade) era vetada",
    files: ["src/agent/guardrails.ts"],
    from: "          if (d < denied.length && denied[d]![0] <= claim.at) continue;\n",
    to: "",
    guard: ["pnpm", "-s", "vitest", "run", "tests/honest-sales-lines.test.ts"],
  },
  {
    id: "R15.3-nem-no-pix",
    bug: "\"Nem no pix tem frete\" passava",
    files: ["src/agent/guardrails.ts"],
    from: "|\\bnem\\b[^.!?,]{0,20}?\\b(?:tem|ha|existe|cobr\\w*|pag\\w*)\\s+(?:o\\s+|de\\s+|nenhum\\s+)?frete\\b",
    to: "",
    guard: ["pnpm", "-s", "vitest", "run", "tests/honest-sales-lines.test.ts"],
  },
  {
    id: "R15.3-so-nega-a-negacao",
    bug: "\"não é grátis só na entrega\" lido como negação honesta",
    files: ["src/agent/guardrails.ts"],
    from: "(?:gratis|gratuit[oa]|de\\s+gra[cs]a|zero)\\b(?!\\s+(?:so|apenas|somente)\\b)",
    to: "(?:gratis|gratuit[oa]|de\\s+gra[cs]a|zero)\\b",
    guard: ["pnpm", "-s", "vitest", "run", "tests/honest-sales-lines.test.ts"],
  },
  {
    id: "R15.3-reticencia",
    bug: "\"…grátis na entrega. No pix também.\" passava",
    files: ["src/agent/guardrails.ts"],
    from: "        if (freeOnDelivery.size > 0) {",
    to: "        if (false) {",
    guard: ["pnpm", "-s", "vitest", "run", "tests/honest-sales-lines.test.ts"],
  },
  {
    id: "R15.3-valor-no-frete",
    bug: "valor atribuído ao frete passava na frase do frete grátis da entrega",
    files: ["src/agent/guardrails.ts"],
    from: "[...t.matchAll(ATTRIBUTED_TO_SHIPPING)].some((m) => !freeOnDelivery.has(startOf(m.index ?? 0)))",
    to: "[...t.matchAll(ATTRIBUTED_TO_SHIPPING)].some(() => false)",
    guard: ["pnpm", "-s", "vitest", "run", "tests/honest-sales-lines.test.ts"],
  },
  {
    id: "R15.3-igual-a-entrega",
    bug: "\"o frete do pix é igual ao da entrega\" passava",
    files: ["src/agent/guardrails.ts"],
    from: "        if (SAME_AS_DELIVERY.test(t)) return",
    to: "        if (false) return",
    guard: ["pnpm", "-s", "vitest", "run", "tests/honest-sales-lines.test.ts"],
  },
  {
    id: "§30-objeto-pelo",
    bug: "\"pode trocar pelo tamanho certo em até 7 dias após o recebimento\" era vetada",
    files: ["src/agent/guardrails.ts", "supabase/functions/turn/guardrails.ts"],
    from: "const OBJECT = String.raw`(?:\\s+(?:de|o|a|pelo|por\\s+outro)\\s+(?:tamanho|produto|colete|numero)(?:\\s+(?:certo|correto|ideal|maior|menor))?)?`;",
    to: "const OBJECT = String.raw`(?:\\s+(?:de|o|a|por\\s+outro)\\s+(?:tamanho|produto|colete|numero))?`;",
    guard: ["pnpm", "-s", "vitest", "run", "tests/honest-sales-lines.test.ts"],
  },
  {
    id: "§30-tem-dias-tamanho",
    bug: "\"Você tem 7 dias pra trocar de tamanho\" era lida como estoque reservado",
    files: ["src/agent/guardrails.ts", "supabase/functions/turn/guardrails.ts"],
    from: "const t = norm(text).replace(/\\b(?:tem|tera)\\s+(?:ate\\s+)?\\w+\\s+(?:dias?|semanas?)\\s+(?:(?:corridos|uteis)\\s+)?(?:pra|para)\\s+(?:troc|devolv)\\w*/g, \" \");",
    to: "const t = norm(text);",
    guard: ["pnpm", "-s", "vitest", "run", "tests/honest-sales-lines.test.ts"],
  },
  {
    id: "§30-tem-sem-contagem",
    bug: "\"Tem pra troca no seu tamanho\" (estoque sem consulta) passaria",
    files: ["src/agent/guardrails.ts", "supabase/functions/turn/guardrails.ts"],
    from: "const t = norm(text).replace(/\\b(?:tem|tera)\\s+(?:ate\\s+)?\\w+\\s+(?:dias?|semanas?)\\s+(?:(?:corridos|uteis)\\s+)?(?:pra|para)\\s+(?:troc|devolv)\\w*/g, \" \");",
    to: "const t = norm(text).replace(/\\b(?:tem|tera)\\s+(?:\\w+\\s+){0,3}?(?:pra|para)\\s+(?:troc|devolv)\\w*/g, \" \");",
    guard: ["pnpm", "-s", "vitest", "run", "tests/honest-sales-lines.test.ts"],
  },
  {
    id: "§31-nao-para-reclamacao",
    bug: "\"Vocês não para de mandar mensagem, que saco\" deixava de ser opt-out",
    files: ["src/agent/guardrails.ts", "supabase/functions/turn/guardrails.ts"],
    from: "    stillSending &&\n    /^(?:(?:e|mas|gente",
    to: "    false &&\n    /^(?:(?:e|mas|gente",
    guard: ["pnpm", "-s", "vitest", "run", "tests/opt-out-gaps.test.ts"],
  },
  {
    id: "§31-nao-para-gosto",
    bug: "\"não para de mandar oferta boa não\" (ela gosta) virava opt-out",
    files: ["src/agent/guardrails.ts", "supabase/functions/turn/guardrails.ts"],
    from: "|\\bquero\\s+ver\\b/.test(t)",
    to: "|\\bquero\\s+ver\\b/.test(\"\")",
    guard: ["pnpm", "-s", "vitest", "run", "tests/opt-out-gaps.test.ts"],
  },
  {
    id: "§31-garantia-oracao",
    bug: "\"Na entrega em média você tem 3 dias pra trocar\" passava",
    files: ["src/agent/guardrails.ts", "supabase/functions/turn/guardrails.ts"],
    from: "        const own = t.slice(0, at).split(/[,;.!?\\n]/).pop()! + (and ? rest.slice(0, and.index) : rest);",
    to: "        const own = t.slice(0, at).split(/[,;.!?\\n]/).pop()!;",
    guard: ["pnpm", "-s", "vitest", "run", "tests/honest-sales-lines.test.ts"],
  },
  {
    id: "§31-teto-sem-contagem",
    bug: "resposta longa sem contagem de dias era vetada pelo teto de custo",
    files: ["src/agent/guardrails.ts", "supabase/functions/turn/guardrails.ts"],
    from: "if (counted > 0 && t.split(",
    to: "if (t.split(",
    guard: ["pnpm", "-s", "vitest", "run", "tests/prepaid-deadline-fuzz.test.ts"],
  },
  {
    id: "§32-frase-inteira",
    bug: "a frase canônica sem âncora no fim deixava \"…grátis na entrega e no site\" passar",
    files: ["src/agent/guardrails.ts", "supabase/functions/turn/guardrails.ts"],
    from: "  return new RegExp(`^${lead}(?:${core})${tail}${courtesy}$`);",
    to: "  return new RegExp(`^${lead}(?:${core})${tail}${courtesy}`);",
    guard: ["pnpm", "-s", "vitest", "run", "tests/honest-sales-lines.test.ts"],
  },
  {
    id: "§32-abertura",
    bug: "qualquer abertura antes da frase canônica deixava passar o antecipado nomeado antes",
    files: ["src/agent/guardrails.ts", "supabase/functions/turn/guardrails.ts"],
    from: "  const lead = `(?:(?:e|ah|ah e|olha|e olha|aqui|e aqui|lembrando que|e lembrando que|so lembrando que),? )?`;",
    to: "  const lead = `(?:.*? )?`;",
    guard: ["pnpm", "-s", "vitest", "run", "tests/honest-sales-lines.test.ts"],
  },
  {
    id: "§32-preco-da-entrega",
    bug: "preço do antecipado aceito na cauda da frase do frete grátis da entrega",
    files: ["src/agent/guardrails.ts", "supabase/functions/turn/guardrails.ts"],
    from: "        const canonical = canonicalFree([codBrl, ...kits.filter((k) => k.path === \"cod\").map((k) => k.priceBrl)], ctx.paymentPath === \"prepay\");",
    to: "        const canonical = canonicalFree([codBrl, prepayBrl, ...kits.map((k) => k.priceBrl)], ctx.paymentPath === \"prepay\");",
    guard: ["pnpm", "-s", "vitest", "run", "tests/honest-sales-lines.test.ts"],
  },
  {
    id: "§32-reticencia-tambem",
    bug: "\"No pix também.\" depois da frase canônica passava",
    files: ["src/agent/guardrails.ts", "supabase/functions/turn/guardrails.ts"],
    from: "const ALSO = /\\b(?:tambem|igua\\w*|mesm[oa]s?|idem)\\b/;",
    to: "const ALSO = /\\b(?:igua\\w*|mesm[oa]s?|idem)\\b/;",
    guard: ["pnpm", "-s", "vitest", "run", "tests/honest-sales-lines.test.ts"],
  },
  {
    id: "§32-reticencia-dois",
    bug: "\"Vale pros dois.\" depois da frase canônica passava",
    files: ["src/agent/guardrails.ts", "supabase/functions/turn/guardrails.ts"],
    from: "|\\b(?:n[oa]s|pr[oa]s|para\\s+[oa]s|em)\\s+(?:dois|duas|ambos|ambas)\\b|\\btod[oa]s",
    to: "|\\btod[oa]s",
    guard: ["pnpm", "-s", "vitest", "run", "tests/honest-sales-lines.test.ts"],
  },
  {
    id: "§32-a-mais-canonica",
    bug: "\"Na entrega e no site, nenhum frete a mais\" passava pela exceção do \"a mais\"",
    files: ["src/agent/guardrails.ts", "supabase/functions/turn/guardrails.ts"],
    from: "            !codFree &&\n            claim.end !== undefined &&",
    to: "            claim.end !== undefined &&",
    guard: ["pnpm", "-s", "vitest", "run", "tests/honest-sales-lines.test.ts"],
  },
  {
    id: "§32-e-nao-e",
    bug: "\"Na entrega em média 3 dias é o prazo pra trocar\" passava: o \"é\" cortava a oração",
    files: ["src/agent/guardrails.ts", "supabase/functions/turn/guardrails.ts"],
    from: "(aligned && accented[at + (c.index ?? 0)] === \"e\")",
    to: "true",
    guard: ["pnpm", "-s", "vitest", "run", "tests/honest-sales-lines.test.ts"],
  },
  {
    id: "§32-e-corta",
    bug: "\"No pix a média é 5 dias e você tem 7 dias de garantia\" era vetada",
    files: ["src/agent/guardrails.ts", "supabase/functions/turn/guardrails.ts"],
    from: "        const own = t.slice(0, at).split(/[,;.!?\\n]/).pop()! + (and ? rest.slice(0, and.index) : rest);",
    to: "        const own = t.slice(0, at).split(/[,;.!?\\n]/).pop()! + rest;",
    guard: ["pnpm", "-s", "vitest", "run", "tests/honest-sales-lines.test.ts"],
  },
  {
    id: "§32-sujeito-de-terceiro",
    bug: "\"Minhas amigas não param de me mandar foto\" virava opt-out",
    files: ["src/agent/guardrails.ts", "supabase/functions/turn/guardrails.ts"],
    from: "    /^(?:(?:e|mas|gente|nossa|aff?e?|oi|ola)\\s+)?(?:(?:voces|vcs|voce|vc|tu|essa\\s+loja|esse\\s+numero|essa\\s+empresa)\\s+)?$/.test(subject) &&",
    to: "    true &&",
    guard: ["pnpm", "-s", "vitest", "run", "tests/opt-out-gaps.test.ts"],
  },
  {
    id: "§32-prompt-frase-canonica",
    bug: "o prompt ensinava uma frase de frete grátis diferente da que o gate aceita",
    files: ["src/agent/prompt.ts", "supabase/functions/turn/prompt.ts"],
    from: "          `ou quando ela perguntar do frete. Use esta frase, com estas palavras, numa frase só dela:`,\n          `\"Pagando na entrega o frete é grátis: você paga só ${money(config.prices.codBrl)} quando receber.\"`,",
    to: "          `ou quando ela perguntar do frete. Use esta frase, com estas palavras, numa frase só dela:`,\n          `\"Pagando na entrega o frete é grátis e você paga só ${money(config.prices.codBrl)} na porta.\"`,",
    guard: ["pnpm", "-s", "vitest", "run", "tests/prompt.test.ts"],
  },
  {
    id: "§32-briefing-frase-canonica",
    bug: "o briefing do gate citava uma frase de frete grátis diferente da canônica",
    files: ["src/agent/guardrails.ts", "supabase/functions/turn/guardrails.ts"],
    from: "numa frase só dela (\"Pagando na entrega o frete é grátis: você paga só ${money(c.prices.codBrl)} quando receber.\"). ",
    to: "numa frase só dela (\"Pagando na entrega o frete é grátis e você paga só ${money(c.prices.codBrl)} na porta.\"). ",
    guard: ["pnpm", "-s", "vitest", "run", "tests/prompt.test.ts"],
  },
  {
    id: "§33-outra-frase-nomeia",
    bug: "'Pagando na entrega o frete é grátis. No pix funciona assim.' passava: a frase que nomeia o pix sem 'também' não era lida",
    files: ["src/agent/guardrails.ts", "supabase/functions/turn/guardrails.ts"],
    from: "            if (!names(s) && !(ALSO.test(s) && (PAYISH.test(s) || prevOther))) continue;",
    to: "            if (!(ALSO.test(s) && (PAYISH.test(s) || prevOther))) continue;",
    guard: ["pnpm", "-s", "vitest", "run", "tests/honest-sales-lines.test.ts"],
  },
  {
    id: "§33-sem-limite",
    bug: "'Isso também vale se você pagar no pix.' passava: a extensão só era lida até seis palavras",
    files: ["src/agent/guardrails.ts", "supabase/functions/turn/guardrails.ts"],
    from: "            if (honest(s)) continue;",
    to: "            if (honest(s) || (s.match(/[a-z0-9]+/g) ?? []).length > 6) continue;",
    guard: ["pnpm", "-s", "vitest", "run", "tests/honest-sales-lines.test.ts"],
  },
  {
    id: "§33-cobrado-ali",
    bug: "a linha do desconto do antecipado ao lado da frase canônica era vetada: dizer que o frete é calculado ali não contava",
    files: ["src/agent/guardrails.ts", "supabase/functions/turn/guardrails.ts"],
    from: "          const honest = (s: string): boolean => /\\b(?:nao|nunca|nem)\\b/.test(s) || FREIGHT_CHARGED.test(s);",
    to: "          const honest = (s: string): boolean => /\\b(?:nao|nunca|nem)\\b/.test(s);",
    guard: ["pnpm", "-s", "vitest", "run", "tests/honest-sales-lines.test.ts"],
  },
  {
    id: "§33-tambem-sem-pagamento",
    bug: "'Isso mesmo!' e 'Eu também uso!' ao lado da frase canônica eram vetadas: 'também/mesmo' sem pagamento nenhum",
    files: ["src/agent/guardrails.ts", "supabase/functions/turn/guardrails.ts"],
    from: "            if (!names(s) && !(ALSO.test(s) && (PAYISH.test(s) || prevOther))) continue;",
    to: "            if (!names(s) && !ALSO.test(s)) continue;",
    guard: ["pnpm", "-s", "vitest", "run", "tests/honest-sales-lines.test.ts"],
  },
  {
    id: "§33-pergunta-antes",
    bug: "'Pagando na entrega o frete é grátis. E antes? Também!' passava: a pergunta antes do 'também' não era lida",
    files: ["src/agent/guardrails.ts", "supabase/functions/turn/guardrails.ts"],
    from: "            const prevOther = prev !== \"\" && !honest(prev) && (names(prev) || PAYISH.test(prev));",
    to: "            const prevOther = false;",
    guard: ["pnpm", "-s", "vitest", "run", "tests/honest-sales-lines.test.ts"],
  },
  {
    id: "§33-antecipado-so-pagando",
    bug: "no caminho antecipado 'Na entrega, o frete é grátis' passava: sem 'pagando', 'na entrega' se lê 'quando chegar'",
    files: ["src/agent/guardrails.ts", "supabase/functions/turn/guardrails.ts"],
    from: "map((k) => k.priceBrl)], ctx.paymentPath === \"prepay\");",
    to: "map((k) => k.priceBrl)], false);",
    guard: ["pnpm", "-s", "vitest", "run", "tests/honest-sales-lines.test.ts"],
  },
  {
    id: "§33-motivo-do-kit",
    bug: "num kit o motivo da reescrita mandava escrever R$ 129,90, que o price_promise veta",
    files: ["src/agent/guardrails.ts", "supabase/functions/turn/guardrails.ts"],
    from: "        const unitPrice = kits.find((k) => k.path === \"cod\" && k.units === ctx.units)?.priceBrl ?? codBrl;",
    to: "        const unitPrice = codBrl;",
    guard: ["pnpm", "-s", "vitest", "run", "tests/honest-sales-lines.test.ts"],
  },
  {
    id: "§33-cortesia",
    bug: "'Pagando na entrega o frete é grátis, tá?' custava uma reescrita",
    files: ["src/agent/guardrails.ts", "supabase/functions/turn/guardrails.ts"],
    from: "  return new RegExp(`^${lead}(?:${core})${tail}${courtesy}$`);",
    to: "  return new RegExp(`^${lead}(?:${core})${tail}$`);",
    guard: ["pnpm", "-s", "vitest", "run", "tests/honest-sales-lines.test.ts"],
  },
  {
    id: "§33-objeto-da-loja",
    bug: "'Nossa, não para de mandar mensagem a transportadora' e 'não param de me mandar SMS de rastreio' viravam opt-out explícito sem sujeito",
    files: ["src/agent/guardrails.ts", "supabase/functions/turn/guardrails.ts"],
    from: "      /^\\s*(?:(?:mais\\s+)?(?:mensage\\w*|msg|promo\\w*|ofertas?|propaganda\\w*|isso|o\\s+saco))?\\s*$/.test(",
    to: "      /(?:)/.test(",
    guard: ["pnpm", "-s", "vitest", "run", "tests/opt-out-gaps.test.ts"],
  },
  {
    id: "§33-prompt-desconto",
    bug: "o prompt ensinava o desconto do antecipado sem dizer que o frete é calculado ali, frase que o gate veta ao lado da canônica",
    files: ["src/agent/prompt.ts", "supabase/functions/turn/prompt.ts"],
    from: "                `é calculado por região no checkout, e você ganha ${config.prices.prepayDiscountPercent}% de desconto: ${money(config.prices.prepayBrl)}.\"`,",
    to: "                `do pix, e você ganha ${config.prices.prepayDiscountPercent}% de desconto: ${money(config.prices.prepayBrl)}.\"`,",
    guard: ["pnpm", "-s", "vitest", "run", "tests/prompt.test.ts"],
  },
  {
    id: "§33-prompt-kit",
    bug: "o prompt não ensinava a frase canônica com o preço do kit, e a de R$ 129,90 é vetada num kit",
    files: ["src/agent/prompt.ts", "supabase/functions/turn/prompt.ts"],
    from: "          ...(config.kits ?? [])\n            .filter((k) => k.path === \"cod\")",
    to: "          ...[]\n            .filter((k) => k.path === \"cod\")",
    guard: ["pnpm", "-s", "vitest", "run", "tests/prompt.test.ts"],
  },
];

const wanted = process.argv.slice(2);
const repo = resolve(".");
const results: Array<{ id: string; caught: boolean; bug: string; note?: string }> = [];

// The mutation list comes from this (working-tree) file, but each mutation is applied to a
// worktree of a commit. With uncommitted edits the two disagree, and the score changed run to
// run on the same HEAD (100, 101, 102/102 — final review, 2026-09-27). So: one commit, read
// once, and a clean tree.
const head = execFileSync("git", ["rev-parse", "HEAD"], { encoding: "utf8" }).trim();
if (execFileSync("git", ["status", "--porcelain", "--untracked-files=no"], { encoding: "utf8" }).trim() !== "") {
  console.error("verificar:guardas: há mudança não commitada — commite antes; a lista de mutações e a árvore mutada precisam ser do mesmo commit.");
  process.exit(2);
}
console.log(`# HEAD ${head.slice(0, 7)}`);

for (const mu of MUTATIONS.filter((m) => wanted.length === 0 || wanted.includes(m.id))) {
  const dir = mkdtempSync(join(tmpdir(), `guard-${mu.id}-`));
  rmSync(dir, { recursive: true, force: true });
  execFileSync("git", ["worktree", "add", "--detach", "-q", dir, head]);
  try {
    symlinkSync(join(repo, "node_modules"), join(dir, "node_modules"));
    let applied = true;
    for (const f of mu.files) {
      const p = join(dir, f);
      let src = readFileSync(p, "utf8");
      for (const e of [{ from: mu.from, to: mu.to }, ...(mu.also ?? [])]) {
        if (!src.includes(e.from)) applied = false;
        else src = src.replace(e.from, e.to);
      }
      writeFileSync(p, src);
    }
    if (!applied) {
      results.push({ id: mu.id, caught: false, bug: mu.bug, note: "a mutação não se aplicou — o texto de origem mudou; atualize a mutação" });
      continue;
    }
    // The guard runs against the mutated tree; the gate diff compares it with HEAD.
    const run = spawnSync(mu.guard[0]!, mu.guard.slice(1), { cwd: dir, encoding: "utf8", timeout: 10 * 60_000 });
    // A guard killed by the timeout or a signal has no status: that is not a catch.
    if (run.status === null) {
      results.push({ id: mu.id, caught: false, bug: mu.bug, note: `inconclusivo — a guarda não terminou (${run.signal ?? run.error?.message ?? "sem status"})` });
      continue;
    }
    results.push({ id: mu.id, caught: run.status !== 0, bug: mu.bug });
  } finally {
    execFileSync("git", ["worktree", "remove", "--force", dir]);
    if (existsSync(dir)) rmSync(dir, { recursive: true, force: true });
  }
}

console.log("# Mutação das guardas — cada bug histórico reinstalado precisa ser pego\n");
for (const r of results) console.log(`- ${r.caught ? "pegou   " : "ESCAPOU "} ${r.id}: ${r.bug}${r.note ? ` (${r.note})` : ""}`);
const escaped = results.filter((r) => !r.caught).length;
console.log(`\n${results.length - escaped}/${results.length} guardas pegaram o próprio bug.`);
process.exitCode = escaped ? 1 : 0;
